// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function GetAgentSessionCommands(arg1:string):Promise<apidto.AgentSessionCommands>;
