// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function ACPAgentInstallPlan(arg1:string):Promise<apidto.ACPInstallPlan>;

export function CanRemoveACPAgent(arg1:string):Promise<boolean>;

export function CancelACPAgentInstall(arg1:string):Promise<void>;

export function InstallACPAgent(arg1:string,arg2:apidto.ACPInstallConfirmation):Promise<apidto.ACPInstallation>;

export function ListInstalledACPAgents():Promise<Array<apidto.ACPInstallation>>;

export function RemoveACPAgent(arg1:string):Promise<void>;

export function UpdateACPAgent(arg1:string,arg2:apidto.ACPInstallConfirmation):Promise<apidto.ACPInstallation>;
