// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ACPAgentInstallPlan(arg1) {
  return window['go']['wailsapi']['ACPInstall']['ACPAgentInstallPlan'](arg1);
}

export function CanRemoveACPAgent(arg1) {
  return window['go']['wailsapi']['ACPInstall']['CanRemoveACPAgent'](arg1);
}

export function CancelACPAgentInstall(arg1) {
  return window['go']['wailsapi']['ACPInstall']['CancelACPAgentInstall'](arg1);
}

export function InstallACPAgent(arg1, arg2) {
  return window['go']['wailsapi']['ACPInstall']['InstallACPAgent'](arg1, arg2);
}

export function ListInstalledACPAgents() {
  return window['go']['wailsapi']['ACPInstall']['ListInstalledACPAgents']();
}

export function RemoveACPAgent(arg1) {
  return window['go']['wailsapi']['ACPInstall']['RemoveACPAgent'](arg1);
}

export function UpdateACPAgent(arg1, arg2) {
  return window['go']['wailsapi']['ACPInstall']['UpdateACPAgent'](arg1, arg2);
}
