// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function GetAgentSessionOptions(arg1:string):Promise<apidto.AgentSessionOptions>;

export function SetAgentSessionOption(arg1:string,arg2:string,arg3:string):Promise<apidto.AgentSessionOptions>;
