// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgentSessionOptions(arg1) {
  return window['go']['wailsapi']['ACPOptions']['GetAgentSessionOptions'](arg1);
}

export function SetAgentSessionOption(arg1, arg2, arg3) {
  return window['go']['wailsapi']['ACPOptions']['SetAgentSessionOption'](arg1, arg2, arg3);
}
