// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function DetectACPAgent(arg1:string):Promise<apidto.ACPAgentSetup>;

export function TestACPAgent(arg1:string,arg2:Array<string>):Promise<apidto.ACPAgentHealth>;
