// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectACPAgent(arg1) {
  return window['go']['wailsapi']['ACPProviders']['DetectACPAgent'](arg1);
}

export function TestACPAgent(arg1, arg2) {
  return window['go']['wailsapi']['ACPProviders']['TestACPAgent'](arg1, arg2);
}
