// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetACPCatalog() {
  return window['go']['wailsapi']['ACPRegistry']['GetACPCatalog']();
}

export function RefreshACPCatalog() {
  return window['go']['wailsapi']['ACPRegistry']['RefreshACPCatalog']();
}
