// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function GetAgentPermissions():Promise<Array<apidto.AgentPermissionView>>;

export function RevokeAgentPermission(arg1:string,arg2:string):Promise<void>;
