// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgentPermissions() {
  return window['go']['wailsapi']['ACPTrust']['GetAgentPermissions']();
}

export function RevokeAgentPermission(arg1, arg2) {
  return window['go']['wailsapi']['ACPTrust']['RevokeAgentPermission'](arg1, arg2);
}
