// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgentConversationWorkDir(arg1) {
  return window['go']['wailsapi']['ACPWorkDir']['GetAgentConversationWorkDir'](arg1);
}

export function SetAgentConversationWorkDir(arg1, arg2) {
  return window['go']['wailsapi']['ACPWorkDir']['SetAgentConversationWorkDir'](arg1, arg2);
}
