// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function GetAgentConversationWorkDir(arg1:string):Promise<apidto.AgentWorkDir>;

export function SetAgentConversationWorkDir(arg1:string,arg2:string):Promise<apidto.AgentWorkDir>;
