// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {allowlist} from '../models';

export function CreateAllowlist(arg1:allowlist.Allowlist):Promise<string>;

export function DeleteAllowlist(arg1:string):Promise<void>;

export function GetAllowlist(arg1:string):Promise<allowlist.Allowlist>;

export function GetAllowlistSearchPaths():Promise<Array<string>>;

export function GetAllowlists():Promise<Array<allowlist.AllowlistInfo>>;

export function RespondQuestionnaire(arg1:string,arg2:Record<string, any>,arg3:boolean):Promise<void>;

export function UpdateAllowlist(arg1:string,arg2:allowlist.Allowlist):Promise<void>;
