// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAllowlist(arg1) {
  return window['go']['wailsapi']['Allowlists']['CreateAllowlist'](arg1);
}

export function DeleteAllowlist(arg1) {
  return window['go']['wailsapi']['Allowlists']['DeleteAllowlist'](arg1);
}

export function GetAllowlist(arg1) {
  return window['go']['wailsapi']['Allowlists']['GetAllowlist'](arg1);
}

export function GetAllowlistSearchPaths() {
  return window['go']['wailsapi']['Allowlists']['GetAllowlistSearchPaths']();
}

export function GetAllowlists() {
  return window['go']['wailsapi']['Allowlists']['GetAllowlists']();
}

export function RespondQuestionnaire(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Allowlists']['RespondQuestionnaire'](arg1, arg2, arg3);
}

export function UpdateAllowlist(arg1, arg2) {
  return window['go']['wailsapi']['Allowlists']['UpdateAllowlist'](arg1, arg2);
}
