// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RetryMessage(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Chat']['RetryMessage'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['Chat']['SendMessage'](arg1, arg2, arg3, arg4);
}
