// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DescribeCommand(arg1, arg2) {
  return window['go']['wailsapi']['CommandCatalog']['DescribeCommand'](arg1, arg2);
}

export function ListCommands(arg1) {
  return window['go']['wailsapi']['CommandCatalog']['ListCommands'](arg1);
}
