// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function DescribeCommand(arg1:string,arg2:apidto.CommandCatalogFilter):Promise<apidto.CommandCatalogDetail>;

export function ListCommands(arg1:apidto.CommandCatalogFilter):Promise<Array<apidto.CommandCatalogItem>>;
