// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {chat} from '../models';
import {apidto} from '../models';

export function AddChildMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<database.ChatMessage>;

export function AddMessage(arg1:string,arg2:string,arg3:string):Promise<database.ChatMessage>;

export function AddMessageWithMedia(arg1:string,arg2:string,arg3:string,arg4:string):Promise<database.ChatMessage>;

export function AddMessageWithTokens(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:string):Promise<database.ChatMessage>;

export function AddMessageWithTokensAndMedia(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:string):Promise<database.ChatMessage>;

export function ClearConversation(arg1:string):Promise<void>;

export function CreateConversation(arg1:string,arg2:string):Promise<database.Conversation>;

export function CreateMessage(arg1:string,arg2:string,arg3:string):Promise<database.ChatMessage>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function DeleteMessages(arg1:string,arg2:Array<string>):Promise<void>;

export function EnsureConversation(arg1:string):Promise<database.Conversation>;

export function GetAllTokenStats():Promise<Record<string, number>>;

export function GetConversation(arg1:string):Promise<database.Conversation>;

export function GetConversationInfo(arg1:string):Promise<database.Conversation>;

export function GetConversationMessageWindow(arg1:chat.MessageWindowRequest):Promise<chat.MessageWindow>;

export function GetConversationSummary(arg1:string):Promise<apidto.ConversationSummaryInfo>;

export function GetConversationWithThreads(arg1:string):Promise<chat.ConversationWithThreads>;

export function GetConversations():Promise<Array<database.Conversation>>;

export function GetConversationsByIDs(arg1:Array<string>):Promise<Array<database.Conversation>>;

export function GetConversationsPage(arg1:number,arg2:number):Promise<database.ConversationListResult>;

export function GetEffectiveModel():Promise<string>;

export function GetMessageChildren(arg1:string):Promise<Array<chat.MessageNode>>;

export function GetMessages(arg1:string,arg2:any):Promise<Array<chat.MessageNode>>;

export function GetMessagesBefore(arg1:string,arg2:string,arg3:number):Promise<Array<chat.MessageNode>>;

export function GetPinnedMessages(arg1:string):Promise<Array<database.ChatMessage>>;

export function GetRecentMessages(arg1:string,arg2:number):Promise<Array<chat.MessageNode>>;

export function RebuildSearchIndex():Promise<void>;

export function RenameConversation(arg1:string,arg2:string):Promise<void>;

export function SearchConversationHistory(arg1:string,arg2:number):Promise<Array<database.MessageSearchResult>>;

export function SetConversationModel(arg1:string,arg2:string):Promise<void>;

export function ToggleMessagePin(arg1:string):Promise<database.ChatMessage>;

export function UpdateConversation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateConversationModel(arg1:string,arg2:string):Promise<void>;

export function UpdateMessage(arg1:string,arg2:string):Promise<void>;
