// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChildMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapi']['Conversations']['AddChildMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function AddMessage(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Conversations']['AddMessage'](arg1, arg2, arg3);
}

export function AddMessageWithMedia(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['Conversations']['AddMessageWithMedia'](arg1, arg2, arg3, arg4);
}

export function AddMessageWithTokens(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['wailsapi']['Conversations']['AddMessageWithTokens'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddMessageWithTokensAndMedia(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['wailsapi']['Conversations']['AddMessageWithTokensAndMedia'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ClearConversation(arg1) {
  return window['go']['wailsapi']['Conversations']['ClearConversation'](arg1);
}

export function CreateConversation(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['CreateConversation'](arg1, arg2);
}

export function CreateMessage(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Conversations']['CreateMessage'](arg1, arg2, arg3);
}

export function DeleteConversation(arg1) {
  return window['go']['wailsapi']['Conversations']['DeleteConversation'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['wailsapi']['Conversations']['DeleteMessage'](arg1);
}

export function DeleteMessages(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['DeleteMessages'](arg1, arg2);
}

export function EnsureConversation(arg1) {
  return window['go']['wailsapi']['Conversations']['EnsureConversation'](arg1);
}

export function GetAllTokenStats() {
  return window['go']['wailsapi']['Conversations']['GetAllTokenStats']();
}

export function GetConversation(arg1) {
  return window['go']['wailsapi']['Conversations']['GetConversation'](arg1);
}

export function GetConversationInfo(arg1) {
  return window['go']['wailsapi']['Conversations']['GetConversationInfo'](arg1);
}

export function GetConversationMessageWindow(arg1) {
  return window['go']['wailsapi']['Conversations']['GetConversationMessageWindow'](arg1);
}

export function GetConversationSummary(arg1) {
  return window['go']['wailsapi']['Conversations']['GetConversationSummary'](arg1);
}

export function GetConversationWithThreads(arg1) {
  return window['go']['wailsapi']['Conversations']['GetConversationWithThreads'](arg1);
}

export function GetConversations() {
  return window['go']['wailsapi']['Conversations']['GetConversations']();
}

export function GetConversationsByIDs(arg1) {
  return window['go']['wailsapi']['Conversations']['GetConversationsByIDs'](arg1);
}

export function GetConversationsPage(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['GetConversationsPage'](arg1, arg2);
}

export function GetEffectiveModel() {
  return window['go']['wailsapi']['Conversations']['GetEffectiveModel']();
}

export function GetMessageChildren(arg1) {
  return window['go']['wailsapi']['Conversations']['GetMessageChildren'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['GetMessages'](arg1, arg2);
}

export function GetMessagesBefore(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Conversations']['GetMessagesBefore'](arg1, arg2, arg3);
}

export function GetRecentMessages(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['GetRecentMessages'](arg1, arg2);
}

export function RebuildSearchIndex() {
  return window['go']['wailsapi']['Conversations']['RebuildSearchIndex']();
}

export function RenameConversation(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['RenameConversation'](arg1, arg2);
}

export function SearchConversationHistory(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['SearchConversationHistory'](arg1, arg2);
}

export function SetConversationModel(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['SetConversationModel'](arg1, arg2);
}

export function UpdateConversation(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Conversations']['UpdateConversation'](arg1, arg2, arg3);
}

export function UpdateConversationModel(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['UpdateConversationModel'](arg1, arg2);
}

export function UpdateMessage(arg1, arg2) {
  return window['go']['wailsapi']['Conversations']['UpdateMessage'](arg1, arg2);
}
