// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCredential(arg1) {
  return window['go']['wailsapi']['Credentials']['DeleteCredential'](arg1);
}

export function ListCredentials() {
  return window['go']['wailsapi']['Credentials']['ListCredentials']();
}

export function ListExternalSources(arg1) {
  return window['go']['wailsapi']['Credentials']['ListExternalSources'](arg1);
}

export function UpsertCredential(arg1) {
  return window['go']['wailsapi']['Credentials']['UpsertCredential'](arg1);
}
