// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function DeleteCredential(arg1:string):Promise<void>;

export function ListCredentials():Promise<Array<apidto.CredentialSummary>>;

export function ListExternalSources(arg1:string):Promise<Array<apidto.ExternalSourceSuggestion>>;

export function UpsertCredential(arg1:apidto.CredentialInput):Promise<void>;
