// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {config} from '../models';

export function ClearMessages():Promise<void>;

export function GetDatabaseStats():Promise<database.DatabaseStats>;

export function GetMaintenanceSettings():Promise<config.MaintenanceSettings>;

export function ResetDatabase():Promise<void>;

export function RunDatabaseMaintenance(arg1:boolean):Promise<database.CompactionResult>;

export function SaveMaintenanceSettings(arg1:config.MaintenanceSettings):Promise<void>;
