// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearMessages() {
  return window['go']['wailsapi']['Database']['ClearMessages']();
}

export function GetDatabaseStats() {
  return window['go']['wailsapi']['Database']['GetDatabaseStats']();
}

export function GetMaintenanceSettings() {
  return window['go']['wailsapi']['Database']['GetMaintenanceSettings']();
}

export function ResetDatabase() {
  return window['go']['wailsapi']['Database']['ResetDatabase']();
}

export function RunDatabaseMaintenance(arg1) {
  return window['go']['wailsapi']['Database']['RunDatabaseMaintenance'](arg1);
}

export function SaveMaintenanceSettings(arg1) {
  return window['go']['wailsapi']['Database']['SaveMaintenanceSettings'](arg1);
}
