// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EditorDeleteDraft(arg1) {
  return window['go']['wailsapi']['Editor']['EditorDeleteDraft'](arg1);
}

export function EditorGetDraftPath(arg1) {
  return window['go']['wailsapi']['Editor']['EditorGetDraftPath'](arg1);
}

export function EditorGetFileInfo(arg1) {
  return window['go']['wailsapi']['Editor']['EditorGetFileInfo'](arg1);
}

export function EditorLoadState() {
  return window['go']['wailsapi']['Editor']['EditorLoadState']();
}

export function EditorOpenFile() {
  return window['go']['wailsapi']['Editor']['EditorOpenFile']();
}

export function EditorReadDraft(arg1) {
  return window['go']['wailsapi']['Editor']['EditorReadDraft'](arg1);
}

export function EditorReadFile(arg1) {
  return window['go']['wailsapi']['Editor']['EditorReadFile'](arg1);
}

export function EditorRenameFile(arg1, arg2) {
  return window['go']['wailsapi']['Editor']['EditorRenameFile'](arg1, arg2);
}

export function EditorSaveFileDialog(arg1) {
  return window['go']['wailsapi']['Editor']['EditorSaveFileDialog'](arg1);
}

export function EditorSaveState(arg1) {
  return window['go']['wailsapi']['Editor']['EditorSaveState'](arg1);
}

export function EditorUnwatchFile(arg1) {
  return window['go']['wailsapi']['Editor']['EditorUnwatchFile'](arg1);
}

export function EditorWatchFile(arg1) {
  return window['go']['wailsapi']['Editor']['EditorWatchFile'](arg1);
}

export function EditorWriteDraft(arg1, arg2) {
  return window['go']['wailsapi']['Editor']['EditorWriteDraft'](arg1, arg2);
}

export function EditorWriteFile(arg1, arg2) {
  return window['go']['wailsapi']['Editor']['EditorWriteFile'](arg1, arg2);
}
