// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function EditorDeleteDraft(arg1:string):Promise<void>;

export function EditorGetDraftPath(arg1:string):Promise<string>;

export function EditorGetFileInfo(arg1:string):Promise<apidto.EditorFileInfo>;

export function EditorLoadState():Promise<apidto.EditorState>;

export function EditorOpenFile(arg1:apidto.FileDialogLabels):Promise<apidto.EditorOpenResult>;

export function EditorReadDraft(arg1:string):Promise<string>;

export function EditorReadFile(arg1:string):Promise<string>;

export function EditorRenameFile(arg1:string,arg2:string):Promise<string>;

export function EditorSaveFileDialog(arg1:string,arg2:apidto.FileDialogLabels):Promise<string>;

export function EditorSaveState(arg1:apidto.EditorState):Promise<void>;

export function EditorUnwatchFile(arg1:string):Promise<void>;

export function EditorWatchFile(arg1:string):Promise<void>;

export function EditorWriteDraft(arg1:string,arg2:string):Promise<void>;

export function EditorWriteFile(arg1:string,arg2:string):Promise<void>;
