// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeImportData(arg1, arg2) {
  return window['go']['wailsapi']['ExportImport']['AnalyzeImportData'](arg1, arg2);
}

export function ExportConversations(arg1) {
  return window['go']['wailsapi']['ExportImport']['ExportConversations'](arg1);
}

export function ExportConversationsToFile(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['ExportImport']['ExportConversationsToFile'](arg1, arg2, arg3, arg4);
}

export function ExportData(arg1) {
  return window['go']['wailsapi']['ExportImport']['ExportData'](arg1);
}

export function ExportDataToFile(arg1, arg2) {
  return window['go']['wailsapi']['ExportImport']['ExportDataToFile'](arg1, arg2);
}

export function ImportConversations(arg1) {
  return window['go']['wailsapi']['ExportImport']['ImportConversations'](arg1);
}

export function ImportData(arg1, arg2) {
  return window['go']['wailsapi']['ExportImport']['ImportData'](arg1, arg2);
}

export function ImportDataWithResolutions(arg1) {
  return window['go']['wailsapi']['ExportImport']['ImportDataWithResolutions'](arg1);
}
