// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto,portability} from '../models';

export function AnalyzeImportData(arg1:string,arg2:string):Promise<portability.ImportAnalysis>;

export function ExportConversations(arg1:Array<string>):Promise<string>;

export function ExportConversationsToFile(arg1:Array<string>,arg2:string,arg3:portability.ContentExportOptions,arg4:apidto.FileDialogLabels):Promise<string>;

export function ExportData(arg1:portability.ExportRequest):Promise<string>;

export function ExportDataToFile(arg1:portability.ExportRequest,arg2:string):Promise<string>;

export function ImportConversations(arg1:string):Promise<portability.ImportResult>;

export function ImportData(arg1:string,arg2:string):Promise<portability.ImportResult>;

export function ImportDataWithResolutions(arg1:portability.ImportRequest):Promise<portability.ImportResult>;
