// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPathDenyEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapi']['FSTrust']['AddPathDenyEntry'](arg1, arg2, arg3, arg4, arg5);
}

export function GetPathAllowlist() {
  return window['go']['wailsapi']['FSTrust']['GetPathAllowlist']();
}

export function RemovePathAllowlistEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapi']['FSTrust']['RemovePathAllowlistEntry'](arg1, arg2, arg3, arg4, arg5);
}
