// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function GetPathAllowlist():Promise<Array<apidto.PathAllowlistView>>;

export function RemovePathAllowlistEntry(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
