// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jobs} from '../models';

export function DeleteJob(arg1:string):Promise<void>;

export function DryRunJob(arg1:string):Promise<jobs.DryRunResult>;

export function GetJob(arg1:string):Promise<jobs.Job>;

export function GetJobEvents(arg1:string):Promise<Array<jobs.EventEntry>>;

export function GetJobEventsPage(arg1:string,arg2:number,arg3:number):Promise<Array<jobs.EventEntry>>;

export function GetJobPipelines():Promise<Array<jobs.PipelineInfo>>;

export function GetJobRuns(arg1:string,arg2:number):Promise<Array<jobs.RunLog>>;

export function GetJobs():Promise<Array<jobs.JobInfo>>;

export function GetToolCatalog():Promise<Array<jobs.CatalogEntry>>;

export function InferEventSchema(arg1:string):Promise<Record<string, any>>;

export function ListKnownEvents():Promise<Array<string>>;

export function RegenerateJobCatalog():Promise<void>;

export function ReplayRun(arg1:string,arg2:string):Promise<jobs.TestToolResult>;

export function RunJob(arg1:string):Promise<jobs.RunLog>;

export function SaveJob(arg1:string):Promise<void>;

export function TestToolDryRun(arg1:string):Promise<jobs.TestToolResult>;

export function ToggleJob(arg1:string,arg2:boolean):Promise<void>;
