// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteJob(arg1) {
  return window['go']['wailsapi']['Jobs']['DeleteJob'](arg1);
}

export function DryRunJob(arg1) {
  return window['go']['wailsapi']['Jobs']['DryRunJob'](arg1);
}

export function GetJob(arg1) {
  return window['go']['wailsapi']['Jobs']['GetJob'](arg1);
}

export function GetJobEvents(arg1) {
  return window['go']['wailsapi']['Jobs']['GetJobEvents'](arg1);
}

export function GetJobEventsPage(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Jobs']['GetJobEventsPage'](arg1, arg2, arg3);
}

export function GetJobPipelines() {
  return window['go']['wailsapi']['Jobs']['GetJobPipelines']();
}

export function GetJobRuns(arg1, arg2) {
  return window['go']['wailsapi']['Jobs']['GetJobRuns'](arg1, arg2);
}

export function GetJobs() {
  return window['go']['wailsapi']['Jobs']['GetJobs']();
}

export function GetToolCatalog() {
  return window['go']['wailsapi']['Jobs']['GetToolCatalog']();
}

export function InferEventSchema(arg1) {
  return window['go']['wailsapi']['Jobs']['InferEventSchema'](arg1);
}

export function ListKnownEvents() {
  return window['go']['wailsapi']['Jobs']['ListKnownEvents']();
}

export function RegenerateJobCatalog() {
  return window['go']['wailsapi']['Jobs']['RegenerateJobCatalog']();
}

export function ReplayRun(arg1, arg2) {
  return window['go']['wailsapi']['Jobs']['ReplayRun'](arg1, arg2);
}

export function RunJob(arg1) {
  return window['go']['wailsapi']['Jobs']['RunJob'](arg1);
}

export function SaveJob(arg1) {
  return window['go']['wailsapi']['Jobs']['SaveJob'](arg1);
}

export function TestToolDryRun(arg1) {
  return window['go']['wailsapi']['Jobs']['TestToolDryRun'](arg1);
}

export function ToggleJob(arg1, arg2) {
  return window['go']['wailsapi']['Jobs']['ToggleJob'](arg1, arg2);
}
