// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function CleanupLegacyChannelJSON(arg1:apidto.CleanupLegacyChannelJSONOptions):Promise<apidto.CleanupLegacyChannelJSONResult>;
