// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStreamingForConversation(arg1) {
  return window['go']['wailsapi']['LLMModels']['CancelStreamingForConversation'](arg1);
}

export function GetModelCatalogByProvider(arg1) {
  return window['go']['wailsapi']['LLMModels']['GetModelCatalogByProvider'](arg1);
}

export function GetModels() {
  return window['go']['wailsapi']['LLMModels']['GetModels']();
}

export function GetModelsByProvider(arg1) {
  return window['go']['wailsapi']['LLMModels']['GetModelsByProvider'](arg1);
}

export function RefreshModelCatalogByProvider(arg1) {
  return window['go']['wailsapi']['LLMModels']['RefreshModelCatalogByProvider'](arg1);
}

export function RefreshModels() {
  return window['go']['wailsapi']['LLMModels']['RefreshModels']();
}

export function RefreshModelsByProvider(arg1) {
  return window['go']['wailsapi']['LLMModels']['RefreshModelsByProvider'](arg1);
}
