// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';

export function CancelStreamingForConversation(arg1:string):Promise<void>;

export function GetModelCatalogByProvider(arg1:string):Promise<llm.ModelCatalog>;

export function GetModels():Promise<Array<string>>;

export function GetModelsByProvider(arg1:string):Promise<Array<string>>;

export function RefreshModelCatalogByProvider(arg1:string):Promise<llm.ModelCatalog>;

export function RefreshModels():Promise<Array<string>>;

export function RefreshModelsByProvider(arg1:string):Promise<Array<string>>;
