// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeChatGPT(arg1, arg2) {
  return window['go']['wailsapi']['LLMProviders']['AuthorizeChatGPT'](arg1, arg2);
}

export function CancelChatGPT(arg1) {
  return window['go']['wailsapi']['LLMProviders']['CancelChatGPT'](arg1);
}

export function ChatGPTConnection(arg1) {
  return window['go']['wailsapi']['LLMProviders']['ChatGPTConnection'](arg1);
}

export function CreateChatGPTConnection(arg1) {
  return window['go']['wailsapi']['LLMProviders']['CreateChatGPTConnection'](arg1);
}

export function CreateDefaultLLMProvider(arg1, arg2) {
  return window['go']['wailsapi']['LLMProviders']['CreateDefaultLLMProvider'](arg1, arg2);
}

export function CreateLLMProvider(arg1) {
  return window['go']['wailsapi']['LLMProviders']['CreateLLMProvider'](arg1);
}

export function DeleteLLMProvider(arg1) {
  return window['go']['wailsapi']['LLMProviders']['DeleteLLMProvider'](arg1);
}

export function DisconnectChatGPT(arg1) {
  return window['go']['wailsapi']['LLMProviders']['DisconnectChatGPT'](arg1);
}

export function GetActiveProviderInfo() {
  return window['go']['wailsapi']['LLMProviders']['GetActiveProviderInfo']();
}

export function GetLLMProvider(arg1) {
  return window['go']['wailsapi']['LLMProviders']['GetLLMProvider'](arg1);
}

export function GetLLMProviders() {
  return window['go']['wailsapi']['LLMProviders']['GetLLMProviders']();
}

export function GetLLMProvidersWithStatus() {
  return window['go']['wailsapi']['LLMProviders']['GetLLMProvidersWithStatus']();
}

export function ListModelsRaw(arg1) {
  return window['go']['wailsapi']['LLMProviders']['ListModelsRaw'](arg1);
}

export function ReloadLLMClient() {
  return window['go']['wailsapi']['LLMProviders']['ReloadLLMClient']();
}

export function SetDefaultProvider(arg1) {
  return window['go']['wailsapi']['LLMProviders']['SetDefaultProvider'](arg1);
}

export function TestLLMProvider(arg1) {
  return window['go']['wailsapi']['LLMProviders']['TestLLMProvider'](arg1);
}

export function UpdateLLMProvider(arg1, arg2) {
  return window['go']['wailsapi']['LLMProviders']['UpdateLLMProvider'](arg1, arg2);
}
