// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';
import {llm} from '../models';

export function CreateDefaultLLMProvider(arg1:string,arg2:string):Promise<void>;

export function CreateLLMProvider(arg1:apidto.CreateLLMProviderRequest):Promise<Record<string, any>>;

export function DeleteLLMProvider(arg1:string):Promise<void>;

export function GetActiveProviderInfo():Promise<Record<string, any>>;

export function GetLLMProvider(arg1:string):Promise<llm.ProviderConfig>;

export function GetLLMProviders():Promise<Array<llm.ProviderConfig>>;

export function GetLLMProvidersWithStatus():Promise<Array<Record<string, any>>>;

export function ListModelsRaw(arg1:apidto.TestLLMProviderRequest):Promise<Array<string>>;

export function ReloadLLMClient():Promise<void>;

export function SetDefaultProvider(arg1:string):Promise<void>;

export function TestLLMProvider(arg1:apidto.TestLLMProviderRequest):Promise<boolean>;

export function UpdateLLMProvider(arg1:string,arg2:apidto.UpdateLLMProviderRequest):Promise<Record<string, any>>;
