// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';
import {apidto} from '../models';

export function ConnectMCPServer(arg1:string):Promise<void>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function DeleteMCPServerAuth(arg1:string):Promise<void>;

export function DisconnectMCPServer(arg1:string):Promise<void>;

export function DiscoverMCPServerAuth(arg1:string):Promise<mcp.OAuthDiscoveryResult>;

export function DuplicateMCPServer(arg1:string):Promise<string>;

export function GetMCPPrompt(arg1:string,arg2:string,arg3:Record<string, string>):Promise<Array<string>>;

export function GetMCPServerAuthInfo(arg1:string):Promise<apidto.MCPServerAuthInfo>;

export function GetMCPServerConfig(arg1:string):Promise<mcp.ServerConfig>;

export function GetMCPServerLogs(arg1:string,arg2:number):Promise<Array<mcp.MCPServerLog>>;

export function GetMCPServerTools(arg1:string):Promise<Array<mcp.MCPToolInfo>>;

export function GetMCPWorkspaceRoots():Promise<Array<mcp.Root>>;

export function ListMCPServers():Promise<Array<mcp.ServerInfo>>;

export function ReadMCPResource(arg1:string,arg2:string):Promise<string>;

export function ReconnectMCPServer(arg1:string):Promise<void>;

export function SaveMCPServer(arg1:string,arg2:mcp.ServerConfig):Promise<void>;

export function SaveMCPServerAuth(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SetMCPWorkspaceRoots(arg1:Array<mcp.Root>):Promise<void>;

export function SubscribeToMCPResource(arg1:string,arg2:string):Promise<void>;

export function UnsubscribeFromMCPResource(arg1:string,arg2:string):Promise<void>;
