// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectMCPServer(arg1) {
  return window['go']['wailsapi']['MCP']['ConnectMCPServer'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['wailsapi']['MCP']['DeleteMCPServer'](arg1);
}

export function DeleteMCPServerAuth(arg1) {
  return window['go']['wailsapi']['MCP']['DeleteMCPServerAuth'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['wailsapi']['MCP']['DisconnectMCPServer'](arg1);
}

export function DiscoverMCPServerAuth(arg1) {
  return window['go']['wailsapi']['MCP']['DiscoverMCPServerAuth'](arg1);
}

export function DuplicateMCPServer(arg1) {
  return window['go']['wailsapi']['MCP']['DuplicateMCPServer'](arg1);
}

export function GetMCPPrompt(arg1, arg2, arg3) {
  return window['go']['wailsapi']['MCP']['GetMCPPrompt'](arg1, arg2, arg3);
}

export function GetMCPServerAuthInfo(arg1) {
  return window['go']['wailsapi']['MCP']['GetMCPServerAuthInfo'](arg1);
}

export function GetMCPServerConfig(arg1) {
  return window['go']['wailsapi']['MCP']['GetMCPServerConfig'](arg1);
}

export function GetMCPServerLogs(arg1, arg2) {
  return window['go']['wailsapi']['MCP']['GetMCPServerLogs'](arg1, arg2);
}

export function GetMCPServerTools(arg1) {
  return window['go']['wailsapi']['MCP']['GetMCPServerTools'](arg1);
}

export function GetMCPWorkspaceRoots() {
  return window['go']['wailsapi']['MCP']['GetMCPWorkspaceRoots']();
}

export function ListMCPServers() {
  return window['go']['wailsapi']['MCP']['ListMCPServers']();
}

export function ReadMCPResource(arg1, arg2) {
  return window['go']['wailsapi']['MCP']['ReadMCPResource'](arg1, arg2);
}

export function ReconnectMCPServer(arg1) {
  return window['go']['wailsapi']['MCP']['ReconnectMCPServer'](arg1);
}

export function SaveMCPServer(arg1, arg2) {
  return window['go']['wailsapi']['MCP']['SaveMCPServer'](arg1, arg2);
}

export function SaveMCPServerAuth(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wailsapi']['MCP']['SaveMCPServerAuth'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetMCPWorkspaceRoots(arg1) {
  return window['go']['wailsapi']['MCP']['SetMCPWorkspaceRoots'](arg1);
}

export function SubscribeToMCPResource(arg1, arg2) {
  return window['go']['wailsapi']['MCP']['SubscribeToMCPResource'](arg1, arg2);
}

export function UnsubscribeFromMCPResource(arg1, arg2) {
  return window['go']['wailsapi']['MCP']['UnsubscribeFromMCPResource'](arg1, arg2);
}
