// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {memory} from '../models';

export function ArchiveMemoryRecord(arg1:string):Promise<database.MemoryRecord>;

export function CreateMemoryRecord(arg1:memory.RecordInput):Promise<database.MemoryRecord>;

export function DeleteMemoryRecord(arg1:string):Promise<void>;

export function GetMemoryPolicySummary():Promise<memory.PolicySummary>;

export function GetMemoryRecord(arg1:string):Promise<database.MemoryRecord>;

export function ListMemoryRecords(arg1:memory.Filter):Promise<memory.ListResult>;

export function SearchMemoryRecords(arg1:string,arg2:memory.Filter):Promise<memory.ListResult>;

export function UnarchiveMemoryRecord(arg1:string,arg2:string):Promise<database.MemoryRecord>;

export function UpdateMemoryRecord(arg1:string,arg2:memory.RecordInput):Promise<database.MemoryRecord>;
