// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveMemoryRecord(arg1) {
  return window['go']['wailsapi']['Memory']['ArchiveMemoryRecord'](arg1);
}

export function CreateMemoryRecord(arg1) {
  return window['go']['wailsapi']['Memory']['CreateMemoryRecord'](arg1);
}

export function DeleteMemoryRecord(arg1) {
  return window['go']['wailsapi']['Memory']['DeleteMemoryRecord'](arg1);
}

export function GetMemoryPolicySummary() {
  return window['go']['wailsapi']['Memory']['GetMemoryPolicySummary']();
}

export function GetMemoryRecord(arg1) {
  return window['go']['wailsapi']['Memory']['GetMemoryRecord'](arg1);
}

export function ListMemoryRecords(arg1) {
  return window['go']['wailsapi']['Memory']['ListMemoryRecords'](arg1);
}

export function SearchMemoryRecords(arg1, arg2) {
  return window['go']['wailsapi']['Memory']['SearchMemoryRecords'](arg1, arg2);
}

export function UnarchiveMemoryRecord(arg1, arg2) {
  return window['go']['wailsapi']['Memory']['UnarchiveMemoryRecord'](arg1, arg2);
}

export function UpdateMemoryRecord(arg1, arg2) {
  return window['go']['wailsapi']['Memory']['UpdateMemoryRecord'](arg1, arg2);
}
