// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {channels} from '../models';
import {contacts} from '../models';
import {controllers} from '../models';
import {apidto} from '../models';

export function AssignConversationToChannel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AuthorizeMessagingContactFull(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateChannelFromTemplate(arg1:string,arg2:Record<string, any>):Promise<void>;

export function GetAllChannelConfigs():Promise<Record<string, channels.ChannelConfig>>;

export function GetAuthorizedContacts():Promise<contacts.ContactsFile>;

export function GetAvailableChannels():Promise<Array<controllers.ChannelInfo>>;

export function GetChannelConfig(arg1:string):Promise<channels.ChannelConfig>;

export function GetChannelConfigAsMap(arg1:string):Promise<Record<string, any>>;

export function GetChannelTemplates():Promise<Array<channels.ChannelTemplate>>;

export function GetConversationChannel(arg1:string):Promise<apidto.ConversationChannel>;

export function GetMessagingStatus():Promise<Record<string, string>>;

export function RemoveAuthorizedContact(arg1:string,arg2:string):Promise<void>;

export function RestartChannel(arg1:string):Promise<void>;

export function SaveChannelConfig(arg1:string,arg2:channels.ChannelConfig):Promise<void>;

export function UnassignConversationFromChannel(arg1:string):Promise<void>;
