// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignConversationToChannel(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Messaging']['AssignConversationToChannel'](arg1, arg2, arg3);
}

export function AuthorizeMessagingContactFull(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['Messaging']['AuthorizeMessagingContactFull'](arg1, arg2, arg3, arg4);
}

export function CreateChannelFromTemplate(arg1, arg2) {
  return window['go']['wailsapi']['Messaging']['CreateChannelFromTemplate'](arg1, arg2);
}

export function GetAllChannelConfigs() {
  return window['go']['wailsapi']['Messaging']['GetAllChannelConfigs']();
}

export function GetAuthorizedContacts() {
  return window['go']['wailsapi']['Messaging']['GetAuthorizedContacts']();
}

export function GetAvailableChannels() {
  return window['go']['wailsapi']['Messaging']['GetAvailableChannels']();
}

export function GetChannelConfig(arg1) {
  return window['go']['wailsapi']['Messaging']['GetChannelConfig'](arg1);
}

export function GetChannelConfigAsMap(arg1) {
  return window['go']['wailsapi']['Messaging']['GetChannelConfigAsMap'](arg1);
}

export function GetChannelTemplates() {
  return window['go']['wailsapi']['Messaging']['GetChannelTemplates']();
}

export function GetConversationChannel(arg1) {
  return window['go']['wailsapi']['Messaging']['GetConversationChannel'](arg1);
}

export function GetMessagingStatus() {
  return window['go']['wailsapi']['Messaging']['GetMessagingStatus']();
}

export function RemoveAuthorizedContact(arg1, arg2) {
  return window['go']['wailsapi']['Messaging']['RemoveAuthorizedContact'](arg1, arg2);
}

export function RestartChannel(arg1) {
  return window['go']['wailsapi']['Messaging']['RestartChannel'](arg1);
}

export function SaveChannelConfig(arg1, arg2) {
  return window['go']['wailsapi']['Messaging']['SaveChannelConfig'](arg1, arg2);
}

export function UnassignConversationFromChannel(arg1) {
  return window['go']['wailsapi']['Messaging']['UnassignConversationFromChannel'](arg1);
}
