// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function GetNetworkAllowlist():Promise<Array<apidto.NetworkAllowlistView>>;

export function RemoveNetworkAllowlistEntry(arg1:string,arg2:string,arg3:string):Promise<void>;
