// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profiles} from '../models';
import {contextprovider} from '../models';

export function CreateProfile(arg1:profiles.Profile):Promise<string>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<string>;

export function GetActiveProfile():Promise<profiles.Profile>;

export function GetActiveProfileAndSlug():Promise<profiles.ActiveProfile>;

export function GetActiveProfileSlug():Promise<string>;

export function GetContextProviders():Promise<Array<contextprovider.ProviderMetadata>>;

export function GetProfile(arg1:string):Promise<profiles.Profile>;

export function GetProfileSearchPaths():Promise<Array<string>>;

export function GetProfiles():Promise<Array<profiles.ProfileInfo>>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:profiles.Profile):Promise<void>;

export function UpdateProfileMediaSupport(arg1:string,arg2:boolean):Promise<void>;
