// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['wailsapi']['Profiles']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['wailsapi']['Profiles']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['wailsapi']['Profiles']['DuplicateProfile'](arg1);
}

export function GetActiveProfile() {
  return window['go']['wailsapi']['Profiles']['GetActiveProfile']();
}

export function GetActiveProfileAndSlug() {
  return window['go']['wailsapi']['Profiles']['GetActiveProfileAndSlug']();
}

export function GetActiveProfileSlug() {
  return window['go']['wailsapi']['Profiles']['GetActiveProfileSlug']();
}

export function GetContextProviders() {
  return window['go']['wailsapi']['Profiles']['GetContextProviders']();
}

export function GetProfile(arg1) {
  return window['go']['wailsapi']['Profiles']['GetProfile'](arg1);
}

export function GetProfileSearchPaths() {
  return window['go']['wailsapi']['Profiles']['GetProfileSearchPaths']();
}

export function GetProfiles() {
  return window['go']['wailsapi']['Profiles']['GetProfiles']();
}

export function SetActiveProfile(arg1) {
  return window['go']['wailsapi']['Profiles']['SetActiveProfile'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['wailsapi']['Profiles']['UpdateProfile'](arg1, arg2);
}

export function UpdateProfileMediaSupport(arg1, arg2) {
  return window['go']['wailsapi']['Profiles']['UpdateProfileMediaSupport'](arg1, arg2);
}
