// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllChannels():Promise<void>;

export function ClearAllCredentials():Promise<void>;

export function ClearAllProfiles():Promise<void>;

export function ClearAllSkills():Promise<void>;

export function GetNativeTTSProviders():Promise<Array<string>>;

export function ResetConfig():Promise<void>;

export function TestConnection():Promise<boolean>;

export function TestConnectionWithModels():Promise<Array<string>>;
