// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllChannels() {
  return window['go']['wailsapi']['Settings']['ClearAllChannels']();
}

export function ClearAllCredentials() {
  return window['go']['wailsapi']['Settings']['ClearAllCredentials']();
}

export function ClearAllProfiles() {
  return window['go']['wailsapi']['Settings']['ClearAllProfiles']();
}

export function ClearAllSkills() {
  return window['go']['wailsapi']['Settings']['ClearAllSkills']();
}

export function GetNativeTTSProviders() {
  return window['go']['wailsapi']['Settings']['GetNativeTTSProviders']();
}

export function ResetConfig() {
  return window['go']['wailsapi']['Settings']['ResetConfig']();
}

export function TestConnection() {
  return window['go']['wailsapi']['Settings']['TestConnection']();
}

export function TestConnectionWithModels() {
  return window['go']['wailsapi']['Settings']['TestConnectionWithModels']();
}
