// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function SignalCheckAPI(arg1:string,arg2:string):Promise<apidto.SignalAPIStatus>;

export function SignalLink(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SignalLinkRaw(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SignalListAccounts(arg1:string,arg2:string):Promise<Array<string>>;

export function SignalRegister(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SignalUnregister(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function SignalVerify(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
