// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SignalCheckAPI(arg1, arg2) {
  return window['go']['wailsapi']['Signal']['SignalCheckAPI'](arg1, arg2);
}

export function SignalLink(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Signal']['SignalLink'](arg1, arg2, arg3);
}

export function SignalLinkRaw(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Signal']['SignalLinkRaw'](arg1, arg2, arg3);
}

export function SignalListAccounts(arg1, arg2) {
  return window['go']['wailsapi']['Signal']['SignalListAccounts'](arg1, arg2);
}

export function SignalRegister(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapi']['Signal']['SignalRegister'](arg1, arg2, arg3, arg4, arg5);
}

export function SignalUnregister(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['Signal']['SignalUnregister'](arg1, arg2, arg3, arg4);
}

export function SignalVerify(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapi']['Signal']['SignalVerify'](arg1, arg2, arg3, arg4);
}
