// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';
import {skills} from '../models';

export function CreateSkill(arg1:apidto.SkillCreateRequest):Promise<string>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DuplicateSkill(arg1:string):Promise<string>;

export function GetSkill(arg1:string):Promise<skills.Skill>;

export function GetSkillSearchPaths():Promise<Array<string>>;

export function GetSkills():Promise<Array<skills.SkillInfo>>;

export function GetUserInvocableSkillsForProfile(arg1:string):Promise<Array<skills.SkillInfo>>;

export function UpdateSkill(arg1:string,arg2:apidto.SkillCreateRequest):Promise<void>;
