// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSkill(arg1) {
  return window['go']['wailsapi']['Skills']['CreateSkill'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['wailsapi']['Skills']['DeleteSkill'](arg1);
}

export function DuplicateSkill(arg1) {
  return window['go']['wailsapi']['Skills']['DuplicateSkill'](arg1);
}

export function GetSkill(arg1) {
  return window['go']['wailsapi']['Skills']['GetSkill'](arg1);
}

export function GetSkillSearchPaths() {
  return window['go']['wailsapi']['Skills']['GetSkillSearchPaths']();
}

export function GetSkills() {
  return window['go']['wailsapi']['Skills']['GetSkills']();
}

export function GetUserInvocableSkillsForProfile(arg1) {
  return window['go']['wailsapi']['Skills']['GetUserInvocableSkillsForProfile'](arg1);
}

export function UpdateSkill(arg1, arg2) {
  return window['go']['wailsapi']['Skills']['UpdateSkill'](arg1, arg2);
}
