// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DispatchSpeech(arg1) {
  return window['go']['wailsapi']['Speech']['DispatchSpeech'](arg1);
}

export function GenerateAndSaveMessageAudio(arg1, arg2) {
  return window['go']['wailsapi']['Speech']['GenerateAndSaveMessageAudio'](arg1, arg2);
}

export function GetMessageAudio(arg1) {
  return window['go']['wailsapi']['Speech']['GetMessageAudio'](arg1);
}

export function GetOpenAITTSVoices() {
  return window['go']['wailsapi']['Speech']['GetOpenAITTSVoices']();
}

export function GetSTTModels(arg1) {
  return window['go']['wailsapi']['Speech']['GetSTTModels'](arg1);
}

export function GetSpeechProviders() {
  return window['go']['wailsapi']['Speech']['GetSpeechProviders']();
}

export function GetTTSModels(arg1) {
  return window['go']['wailsapi']['Speech']['GetTTSModels'](arg1);
}

export function GetTTSVoices(arg1, arg2) {
  return window['go']['wailsapi']['Speech']['GetTTSVoices'](arg1, arg2);
}

export function InitSpeechManagerFromProfile() {
  return window['go']['wailsapi']['Speech']['InitSpeechManagerFromProfile']();
}

export function SaveMessageAudio(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Speech']['SaveMessageAudio'](arg1, arg2, arg3);
}

export function SetOpenAITTSSpeed(arg1) {
  return window['go']['wailsapi']['Speech']['SetOpenAITTSSpeed'](arg1);
}

export function SetOpenAITTSVoice(arg1) {
  return window['go']['wailsapi']['Speech']['SetOpenAITTSVoice'](arg1);
}

export function SpeakMessage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wailsapi']['Speech']['SpeakMessage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SpeakPreview(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['wailsapi']['Speech']['SpeakPreview'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SynthesizeOpenAI(arg1) {
  return window['go']['wailsapi']['Speech']['SynthesizeOpenAI'](arg1);
}

export function SynthesizeOpenAIStream(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Speech']['SynthesizeOpenAIStream'](arg1, arg2, arg3);
}

export function SynthesizeOpenAIWithVoice(arg1, arg2) {
  return window['go']['wailsapi']['Speech']['SynthesizeOpenAIWithVoice'](arg1, arg2);
}

export function TranscribeWhisper(arg1, arg2) {
  return window['go']['wailsapi']['Speech']['TranscribeWhisper'](arg1, arg2);
}
