// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';
import {speech} from '../models';
import {llm} from '../models';

export function DispatchSpeech(arg1:apidto.ChatSpeakRequest):Promise<void>;

export function GenerateAndSaveMessageAudio(arg1:string,arg2:string):Promise<speech.AudioResult>;

export function GetMessageAudio(arg1:string):Promise<speech.AudioResult>;

export function GetOpenAITTSVoices():Promise<Array<speech.TTSVoiceInfo>>;

export function GetSTTModels(arg1:string):Promise<Array<speech.SpeechModelInfo>>;

export function GetSpeechProviders():Promise<Array<llm.ProviderConfig>>;

export function GetTTSModels(arg1:string):Promise<Array<speech.TTSModelInfo>>;

export function GetTTSVoices(arg1:string,arg2:string):Promise<Array<speech.TTSVoiceInfo>>;

export function InitSpeechManagerFromProfile():Promise<void>;

export function SaveMessageAudio(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetOpenAITTSSpeed(arg1:number):Promise<void>;

export function SetOpenAITTSVoice(arg1:string):Promise<void>;

export function SpeakMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<speech.AudioResult>;

export function SpeakPreview(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string,arg8:string):Promise<void>;

export function SynthesizeOpenAI(arg1:string):Promise<apidto.SynthesisResultInfo>;

export function SynthesizeOpenAIStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SynthesizeOpenAIWithVoice(arg1:string,arg2:string):Promise<apidto.SynthesisResultInfo>;

export function TranscribeWhisper(arg1:string,arg2:string):Promise<speech.TranscriptionResult>;
