// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSubAgentRun(arg1, arg2) {
  return window['go']['wailsapi']['Subagent']['CancelSubAgentRun'](arg1, arg2);
}

export function ListSubAgentRuns(arg1) {
  return window['go']['wailsapi']['Subagent']['ListSubAgentRuns'](arg1);
}
