// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {subagent} from '../models';

export function CancelSubAgentRun(arg1:string,arg2:string):Promise<subagent.CancelResult>;

export function ListSubAgentRuns(arg1:number):Promise<subagent.RunListResult>;
