// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function ClearTaskList(arg1:string):Promise<void>;

export function CloneTaskList(arg1:string,arg2:string):Promise<database.TaskList>;

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:any):Promise<database.Task>;

export function CreateTaskList(arg1:string,arg2:string,arg3:string):Promise<database.TaskList>;

export function CreateTaskNote(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<database.TaskNote>;

export function DeleteTask(arg1:string):Promise<void>;

export function DeleteTaskList(arg1:string):Promise<void>;

export function DeleteTaskNote(arg1:string):Promise<void>;

export function DemoteTask(arg1:string,arg2:string):Promise<void>;

export function GetAllTaskLists():Promise<Array<database.TaskList>>;

export function GetSubtasks(arg1:string):Promise<Array<database.Task>>;

export function GetTask(arg1:string):Promise<database.Task>;

export function GetTaskCountsByStatus(arg1:string):Promise<Record<number, number>>;

export function GetTaskList(arg1:string):Promise<database.TaskList>;

export function GetTaskListStats(arg1:string):Promise<Record<string, any>>;

export function GetTaskListWithHierarchy(arg1:string):Promise<database.TaskList>;

export function GetTaskListsByConversation(arg1:string):Promise<Array<database.TaskList>>;

export function GetTaskNotes(arg1:string):Promise<Array<database.TaskNote>>;

export function GetTasksByConversation(arg1:string):Promise<Array<database.Task>>;

export function GetTasksByStatus(arg1:string,arg2:number):Promise<Array<database.Task>>;

export function GetTasksByTaskListID(arg1:string):Promise<Array<database.Task>>;

export function GetWorkflow(arg1:string):Promise<database.TaskListWorkflow>;

export function PromoteTask(arg1:string):Promise<void>;

export function ReorderTasks(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function ReorderWorkflowStatuses(arg1:string,arg2:Array<number>):Promise<void>;

export function SetTaskConversation(arg1:string,arg2:any):Promise<void>;

export function SetTaskListConversation(arg1:string,arg2:any):Promise<void>;

export function SetTaskListViewMode(arg1:string,arg2:string):Promise<void>;

export function UpdateTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateTaskAssignee(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateTaskFull(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<void>;

export function UpdateTaskList(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateTaskNote(arg1:string,arg2:string):Promise<void>;

export function UpdateTaskStatus(arg1:string,arg2:number):Promise<void>;

export function UpdateWorkflow(arg1:string,arg2:Array<database.TaskListWorkflowStatus>,arg3:Record<number, Array<number>>):Promise<void>;

export function UpdateWorkflowFull(arg1:string,arg2:Array<database.TaskListWorkflowStatus>,arg3:Record<number, Array<number>>,arg4:number,arg5:Record<number, number>):Promise<void>;

export function ValidateStatusTransition(arg1:string,arg2:number,arg3:number):Promise<void>;
