// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {apidto} from '../models';

export function GetTaskListCustomActions(arg1:string):Promise<database.TaskListCustomActions>;

export function ListBoardCustomActions(arg1:string):Promise<Array<apidto.CustomActionView>>;

export function ListCardCustomActions(arg1:string,arg2:string):Promise<Array<apidto.CustomActionView>>;

export function SetTaskListCustomActions(arg1:string,arg2:string):Promise<void>;

export function TriggerCustomAction(arg1:string,arg2:string,arg3:string):Promise<string>;
