// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTaskList(arg1) {
  return window['go']['wailsapi']['Tasklist']['ClearTaskList'](arg1);
}

export function CloneTaskList(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['CloneTaskList'](arg1, arg2);
}

export function CreateTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wailsapi']['Tasklist']['CreateTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTaskList(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Tasklist']['CreateTaskList'](arg1, arg2, arg3);
}

export function CreateTaskNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapi']['Tasklist']['CreateTaskNote'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteTask(arg1) {
  return window['go']['wailsapi']['Tasklist']['DeleteTask'](arg1);
}

export function DeleteTaskList(arg1) {
  return window['go']['wailsapi']['Tasklist']['DeleteTaskList'](arg1);
}

export function DeleteTaskNote(arg1) {
  return window['go']['wailsapi']['Tasklist']['DeleteTaskNote'](arg1);
}

export function DemoteTask(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['DemoteTask'](arg1, arg2);
}

export function GetAllTaskLists() {
  return window['go']['wailsapi']['Tasklist']['GetAllTaskLists']();
}

export function GetSubtasks(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetSubtasks'](arg1);
}

export function GetTask(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTask'](arg1);
}

export function GetTaskCountsByStatus(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTaskCountsByStatus'](arg1);
}

export function GetTaskList(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTaskList'](arg1);
}

export function GetTaskListStats(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTaskListStats'](arg1);
}

export function GetTaskListWithHierarchy(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTaskListWithHierarchy'](arg1);
}

export function GetTaskListsByConversation(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTaskListsByConversation'](arg1);
}

export function GetTaskNotes(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTaskNotes'](arg1);
}

export function GetTasksByConversation(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTasksByConversation'](arg1);
}

export function GetTasksByStatus(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['GetTasksByStatus'](arg1, arg2);
}

export function GetTasksByTaskListID(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetTasksByTaskListID'](arg1);
}

export function GetWorkflow(arg1) {
  return window['go']['wailsapi']['Tasklist']['GetWorkflow'](arg1);
}

export function PromoteTask(arg1) {
  return window['go']['wailsapi']['Tasklist']['PromoteTask'](arg1);
}

export function ReorderTasks(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Tasklist']['ReorderTasks'](arg1, arg2, arg3);
}

export function ReorderWorkflowStatuses(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['ReorderWorkflowStatuses'](arg1, arg2);
}

export function SetTaskConversation(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['SetTaskConversation'](arg1, arg2);
}

export function SetTaskListConversation(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['SetTaskListConversation'](arg1, arg2);
}

export function SetTaskListViewMode(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['SetTaskListViewMode'](arg1, arg2);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapi']['Tasklist']['UpdateTask'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTaskAssignee(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Tasklist']['UpdateTaskAssignee'](arg1, arg2, arg3);
}

export function UpdateTaskFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['wailsapi']['Tasklist']['UpdateTaskFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateTaskList(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Tasklist']['UpdateTaskList'](arg1, arg2, arg3);
}

export function UpdateTaskNote(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['UpdateTaskNote'](arg1, arg2);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['wailsapi']['Tasklist']['UpdateTaskStatus'](arg1, arg2);
}

export function UpdateWorkflow(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Tasklist']['UpdateWorkflow'](arg1, arg2, arg3);
}

export function UpdateWorkflowFull(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wailsapi']['Tasklist']['UpdateWorkflowFull'](arg1, arg2, arg3, arg4, arg5);
}

export function ValidateStatusTransition(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Tasklist']['ValidateStatusTransition'](arg1, arg2, arg3);
}
