// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminalSession(arg1) {
  return window['go']['wailsapi']['Terminal']['CloseTerminalSession'](arg1);
}

export function CreateTerminalSession(arg1) {
  return window['go']['wailsapi']['Terminal']['CreateTerminalSession'](arg1);
}

export function GetTerminalHistory(arg1) {
  return window['go']['wailsapi']['Terminal']['GetTerminalHistory'](arg1);
}

export function GetTerminalStats() {
  return window['go']['wailsapi']['Terminal']['GetTerminalStats']();
}

export function InterruptTerminalCommand(arg1) {
  return window['go']['wailsapi']['Terminal']['InterruptTerminalCommand'](arg1);
}

export function ListTerminalSessions() {
  return window['go']['wailsapi']['Terminal']['ListTerminalSessions']();
}

export function RunTerminalCommand(arg1, arg2) {
  return window['go']['wailsapi']['Terminal']['RunTerminalCommand'](arg1, arg2);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['wailsapi']['Terminal']['SendTerminalInput'](arg1, arg2);
}
