// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';

export function CloseTerminalSession(arg1:string):Promise<void>;

export function CreateTerminalSession(arg1:string):Promise<terminal.SessionInfo>;

export function GetTerminalHistory(arg1:string):Promise<Array<terminal.HistoryEntry>>;

export function GetTerminalStats():Promise<terminal.ManagerStats>;

export function InterruptTerminalCommand(arg1:string):Promise<void>;

export function ListTerminalSessions():Promise<Array<terminal.SessionInfo>>;

export function RunTerminalCommand(arg1:string,arg2:string):Promise<void>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;
