// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function CheckContextWindowThreshold(arg1:string,arg2:number):Promise<boolean>;

export function GetConversationTokenStats(arg1:string):Promise<chat.TokenStats>;

export function GetRecentMessagesTokenCount(arg1:string,arg2:number):Promise<number>;

export function GetTurnTokenStats(arg1:string,arg2:string):Promise<chat.TokenStats>;
