// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckContextWindowThreshold(arg1, arg2) {
  return window['go']['wailsapi']['Tokens']['CheckContextWindowThreshold'](arg1, arg2);
}

export function GetConversationTokenStats(arg1) {
  return window['go']['wailsapi']['Tokens']['GetConversationTokenStats'](arg1);
}

export function GetRecentMessagesTokenCount(arg1, arg2) {
  return window['go']['wailsapi']['Tokens']['GetRecentMessagesTokenCount'](arg1, arg2);
}

export function GetTurnTokenStats(arg1, arg2) {
  return window['go']['wailsapi']['Tokens']['GetTurnTokenStats'](arg1, arg2);
}
