// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableTools() {
  return window['go']['wailsapi']['Tools']['GetAvailableTools']();
}

export function GetRuntimeToolCatalog(arg1) {
  return window['go']['wailsapi']['Tools']['GetRuntimeToolCatalog'](arg1);
}
