// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apidto} from '../models';

export function GetAvailableTools():Promise<Array<apidto.ToolInfo>>;

export function GetRuntimeToolCatalog(arg1:apidto.RuntimeToolCatalogFilter):Promise<Array<apidto.RuntimeToolCatalogEntry>>;
