// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['wailsapi']['Updater']['ApplyUpdate']();
}

export function CheckForUpdates() {
  return window['go']['wailsapi']['Updater']['CheckForUpdates']();
}

export function GetAppVersion() {
  return window['go']['wailsapi']['Updater']['GetAppVersion']();
}

export function StartUpdate() {
  return window['go']['wailsapi']['Updater']['StartUpdate']();
}
