// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function GetAppVersion():Promise<string>;

export function StartUpdate():Promise<void>;
