// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NeedsWelcomeWizard() {
  return window['go']['wailsapi']['Welcome']['NeedsWelcomeWizard']();
}

export function RunWelcomeWizard() {
  return window['go']['wailsapi']['Welcome']['RunWelcomeWizard']();
}
