// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NeedsWelcomeWizard():Promise<boolean>;

export function RunWelcomeWizard():Promise<boolean>;
