// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspaceTab(arg1) {
  return window['go']['wailsapi']['Workspace']['AddWorkspaceTab'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['wailsapi']['Workspace']['CreateWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['wailsapi']['Workspace']['DeleteWorkspace'](arg1);
}

export function ExportWorkspace() {
  return window['go']['wailsapi']['Workspace']['ExportWorkspace']();
}

export function GetActiveWorkspace() {
  return window['go']['wailsapi']['Workspace']['GetActiveWorkspace']();
}

export function ImportWorkspace(arg1) {
  return window['go']['wailsapi']['Workspace']['ImportWorkspace'](arg1);
}

export function ListWorkspaces() {
  return window['go']['wailsapi']['Workspace']['ListWorkspaces']();
}

export function MoveWorkspaceTabTo(arg1, arg2) {
  return window['go']['wailsapi']['Workspace']['MoveWorkspaceTabTo'](arg1, arg2);
}

export function RemoveWorkspaceTab(arg1) {
  return window['go']['wailsapi']['Workspace']['RemoveWorkspaceTab'](arg1);
}

export function RenameWorkspace(arg1) {
  return window['go']['wailsapi']['Workspace']['RenameWorkspace'](arg1);
}

export function ReorderWorkspaceTabs(arg1) {
  return window['go']['wailsapi']['Workspace']['ReorderWorkspaceTabs'](arg1);
}

export function SaveWorkspace() {
  return window['go']['wailsapi']['Workspace']['SaveWorkspace']();
}

export function SetActiveWorkspaceTab(arg1) {
  return window['go']['wailsapi']['Workspace']['SetActiveWorkspaceTab'](arg1);
}

export function SetWorkspaceProfile(arg1) {
  return window['go']['wailsapi']['Workspace']['SetWorkspaceProfile'](arg1);
}

export function SwitchWorkspace(arg1) {
  return window['go']['wailsapi']['Workspace']['SwitchWorkspace'](arg1);
}

export function UpdateWorkspaceTab(arg1, arg2) {
  return window['go']['wailsapi']['Workspace']['UpdateWorkspaceTab'](arg1, arg2);
}
