// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';

export function AddWorkspaceTab(arg1:workspace.Tab):Promise<workspace.Workspace>;

export function CreateWorkspace(arg1:string):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function ExportWorkspace():Promise<string>;

export function GetActiveWorkspace():Promise<workspace.Workspace>;

export function ImportWorkspace(arg1:string):Promise<workspace.Workspace>;

export function ListWorkspaces():Promise<Array<workspace.WorkspaceInfo>>;

export function MoveWorkspaceTabTo(arg1:string,arg2:string):Promise<workspace.Workspace>;

export function RemoveWorkspaceTab(arg1:string):Promise<workspace.Workspace>;

export function RenameWorkspace(arg1:string):Promise<void>;

export function ReorderWorkspaceTabs(arg1:Array<string>):Promise<void>;

export function SaveWorkspace():Promise<void>;

export function SetActiveWorkspaceTab(arg1:string):Promise<void>;

export function SetWorkspaceProfile(arg1:string):Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<workspace.Workspace>;

export function UpdateWorkspaceTab(arg1:string,arg2:Record<string, any>):Promise<void>;
