import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ProviderForm } from './ProviderForm';
import { CreateLLMProvider, ListModelsRaw } from '@wailsjs/go/wailsapi/LLMProviders';
import { GetCredentialForURL, UpsertCredential } from '@wailsjs/go/wailsapi/Credentials';
vi.mock('react-i18next', () => ({ initReactI18next: { type: '3rdParty', init: () => {} }, useTranslation: () => ({ t: (key: string) => key, i18n: { language: 'en' } }) }));
vi.mock('../../hooks/useAnnouncer', () => ({ useAnnouncer: () => ({ announce: vi.fn() }) }));
vi.mock('@wailsjs/go/wailsapi/LLMProviders', () => ({ ListModelsRaw: vi.fn(), CreateLLMProvider: vi.fn(), UpdateLLMProvider: vi.fn() }));
vi.mock('@wailsjs/go/wailsapi/Credentials', () => ({ GetCredentialForURL: vi.fn(), ListCredentials: vi.fn(async () => []), ListExternalSources: vi.fn(async () => []), UpsertCredential: vi.fn() }));
beforeEach(() => {
 vi.clearAllMocks();
 vi.mocked(GetCredentialForURL).mockResolvedValue(null!);
 vi.mocked(ListModelsRaw).mockResolvedValue(['model']);
 vi.mocked(CreateLLMProvider).mockResolvedValue({});
});
const configure = async () => {
 const button = screen.getByRole('button', { name: 'credentials.mcp.configure' });
 await waitFor(() => expect(button).toBeEnabled());
 await userEvent.click(button);
};
const set = async (label: string, value: string) => { await act(async () => { fireEvent.change(screen.getByLabelText(new RegExp(label)), { target: { value } }); }); };
describe('ProviderForm shared credentials', () => {
 it.each(['static', 'env', 'keyring', 'command'])('tests and saves a %s draft through the provider transaction only', async source => {
  const saved = vi.fn();
  render(<ProviderForm onSave={saved} onCancel={() => {}} />);
  expect(ListModelsRaw).not.toHaveBeenCalled();
  await set('providerForm.name', 'Gateway');
  await configure();
  await set('credentials.sourceFields.source', source);
  if (source === 'static') await set('credentials.labels.token', 'private-token');
  if (source === 'env') await set('credentials.sourceFields.envName', 'API_TOKEN');
  if (source === 'keyring') await set('credentials.sourceFields.keyringName', 'api-target');
  if (source === 'command') await set('credentials.sourceFields.commandName', 'token-command');
  expect(ListModelsRaw).not.toHaveBeenCalled();
  await userEvent.click(screen.getByRole('button', { name: 'providerForm.loadModels' }));
  await screen.findByText('providerForm.connected');
  const preview = vi.mocked(ListModelsRaw).mock.calls[0][0];
  expect(preview.credential).toEqual(expect.objectContaining({ source, pattern: 'api.openai.com', type: 'bearer' }));
  expect(preview.api_key).toBeUndefined();
  await userEvent.click(screen.getByRole('button', { name: 'common.create' }));
  await waitFor(() => expect(saved).toHaveBeenCalledOnce());
  expect(vi.mocked(CreateLLMProvider).mock.calls[0][0].credential).toEqual(preview.credential);
  expect(UpsertCredential).not.toHaveBeenCalled();
 });
 it('does not submit when configuring or keeping a credential', async () => {
  const submitted = vi.fn();
  const { container } = render(<ProviderForm onSave={() => {}} onCancel={() => {}} />);
  container.querySelector('form')!.addEventListener('submit', submitted);
  await configure();
  await userEvent.click(screen.getByRole('button', { name: 'credentials.mcp.keepExisting' }));
  expect(submitted).not.toHaveBeenCalled();
  expect(CreateLLMProvider).not.toHaveBeenCalled();
 });
 it('invalidates testing on source changes and discards a late result after URL change', async () => {
  let resolve!: (models: string[]) => void;
  vi.mocked(ListModelsRaw).mockReturnValue(new Promise(done => { resolve = done; }));
  render(<ProviderForm onSave={() => {}} onCancel={() => {}} />);
  await set('providerForm.providerType', 'custom');
  await set('Base URL', 'https://one.example/v1');
  await userEvent.click(screen.getByRole('button', { name: 'providerForm.loadModels' }));
  await set('Base URL', 'https://two.example/v1');
  await act(async () => resolve(['old-model']));
  expect(screen.queryByText('providerForm.connected')).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'common.create' })).toBeDisabled();
  vi.mocked(ListModelsRaw).mockResolvedValue(['current-model']);
  await userEvent.click(screen.getByRole('button', { name: 'providerForm.loadModels' }));
  await screen.findByText('providerForm.connected');
  await configure();
  await set('credentials.sourceFields.source', 'env');
  await set('credentials.sourceFields.envName', 'OTHER_TOKEN');
  expect(screen.getByRole('button', { name: 'common.create' })).toBeDisabled();
 });
 it('keeps editing and cancellation blocked until the save resolves', async () => {
  let resolve!: (value: Record<string, never>) => void;
  vi.mocked(CreateLLMProvider).mockReturnValue(new Promise(done => { resolve = done; }));
  const busy = vi.fn(); const saved = vi.fn();
  render(<ProviderForm onSave={saved} onCancel={() => {}} onBusyChange={busy} />);
  await set('providerForm.name', 'Gateway');
  await userEvent.click(screen.getByRole('button', { name: 'providerForm.loadModels' }));
  await screen.findByText('providerForm.connected');
  await userEvent.click(screen.getByRole('button', { name: 'common.create' }));
  expect(screen.getByLabelText(/providerForm.name/)).toBeDisabled();
  expect(screen.getByRole('button', { name: 'common.cancel' })).toBeDisabled();
  expect(busy).toHaveBeenLastCalledWith(true);
  await act(async () => resolve({}));
  expect(saved).toHaveBeenCalledOnce();
  expect(busy).toHaveBeenLastCalledWith(false);
 });
});
