// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {app} from '../models';
import {database} from '../models';
import {llm} from '../models';
import {credentials} from '../models';
import {ports} from '../models';

export function CanPersistCredentials():Promise<boolean>;

export function Context():Promise<context.Context>;

export function CreateAdminUser(arg1:app.CreateAdminRequest):Promise<database.User>;

export function GetAuthStatus():Promise<app.AuthStatus>;

export function GetAuthUser():Promise<app.AuthUser>;

export function GetVaultIntegrityStatus():Promise<credentials.VaultIntegrityStatus>;

export function HasMasterKey():Promise<boolean>;

export function Login(arg1:app.LoginRequest):Promise<app.AuthUser>;

export function Logout(arg1:app.LogoutRequest):Promise<void>;

export function RefreshAuth(arg1:app.RefreshRequest):Promise<app.AuthUser>;

export function RetryUserRuntimeInit():Promise<app.RuntimePartialInitPayload>;

export function SendMessageSync(arg1:Array<llm.Message>,arg2:llm.ChatParams):Promise<string>;

export function SetupMasterPassword(arg1:string):Promise<string>;

export function SetupVault(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function Shutdown():Promise<void>;

export function StartupWithAdapters(arg1:context.Context,arg2:ports.Emitter,arg3:ports.WindowPort,arg4:ports.SystemDialogPort):Promise<void>;

export function UnlockVault(arg1:string,arg2:string):Promise<void>;
