// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspaceTab(arg1) {
  return window['go']['app']['App']['AddWorkspaceTab'](arg1);
}

export function AnalyzeImportData(arg1, arg2) {
  return window['go']['app']['App']['AnalyzeImportData'](arg1, arg2);
}

export function AssignConversationToChannel(arg1, arg2, arg3) {
  return window['go']['app']['App']['AssignConversationToChannel'](arg1, arg2, arg3);
}

export function AuthorizeMessagingContactFull(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AuthorizeMessagingContactFull'](arg1, arg2, arg3, arg4);
}

export function CanPersistCredentials() {
  return window['go']['app']['App']['CanPersistCredentials']();
}

export function CancelStreamingForConversation(arg1) {
  return window['go']['app']['App']['CancelStreamingForConversation'](arg1);
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function CreateAdminUser(arg1) {
  return window['go']['app']['App']['CreateAdminUser'](arg1);
}

export function CreateChannelFromTemplate(arg1, arg2) {
  return window['go']['app']['App']['CreateChannelFromTemplate'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['app']['App']['CreateWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['app']['App']['DeleteWorkspace'](arg1);
}

export function EditorDeleteDraft(arg1) {
  return window['go']['app']['App']['EditorDeleteDraft'](arg1);
}

export function EditorGetDraftPath(arg1) {
  return window['go']['app']['App']['EditorGetDraftPath'](arg1);
}

export function EditorGetFileInfo(arg1) {
  return window['go']['app']['App']['EditorGetFileInfo'](arg1);
}

export function EditorLoadState() {
  return window['go']['app']['App']['EditorLoadState']();
}

export function EditorOpenFile() {
  return window['go']['app']['App']['EditorOpenFile']();
}

export function EditorReadDraft(arg1) {
  return window['go']['app']['App']['EditorReadDraft'](arg1);
}

export function EditorReadFile(arg1) {
  return window['go']['app']['App']['EditorReadFile'](arg1);
}

export function EditorRenameFile(arg1, arg2) {
  return window['go']['app']['App']['EditorRenameFile'](arg1, arg2);
}

export function EditorSaveFileDialog(arg1) {
  return window['go']['app']['App']['EditorSaveFileDialog'](arg1);
}

export function EditorSaveState(arg1) {
  return window['go']['app']['App']['EditorSaveState'](arg1);
}

export function EditorUnwatchFile(arg1) {
  return window['go']['app']['App']['EditorUnwatchFile'](arg1);
}

export function EditorWatchFile(arg1) {
  return window['go']['app']['App']['EditorWatchFile'](arg1);
}

export function EditorWriteDraft(arg1, arg2) {
  return window['go']['app']['App']['EditorWriteDraft'](arg1, arg2);
}

export function EditorWriteFile(arg1, arg2) {
  return window['go']['app']['App']['EditorWriteFile'](arg1, arg2);
}

export function ExportConversations(arg1) {
  return window['go']['app']['App']['ExportConversations'](arg1);
}

export function ExportConversationsToFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportConversationsToFile'](arg1, arg2, arg3);
}

export function ExportData(arg1) {
  return window['go']['app']['App']['ExportData'](arg1);
}

export function ExportDataToFile(arg1, arg2) {
  return window['go']['app']['App']['ExportDataToFile'](arg1, arg2);
}

export function ExportWorkspace() {
  return window['go']['app']['App']['ExportWorkspace']();
}

export function GetActiveWorkspace() {
  return window['go']['app']['App']['GetActiveWorkspace']();
}

export function GetAllChannelConfigs() {
  return window['go']['app']['App']['GetAllChannelConfigs']();
}

export function GetAuthStatus() {
  return window['go']['app']['App']['GetAuthStatus']();
}

export function GetAuthUser() {
  return window['go']['app']['App']['GetAuthUser']();
}

export function GetAuthorizedContacts() {
  return window['go']['app']['App']['GetAuthorizedContacts']();
}

export function GetAvailableChannels() {
  return window['go']['app']['App']['GetAvailableChannels']();
}

export function GetChannelConfig(arg1) {
  return window['go']['app']['App']['GetChannelConfig'](arg1);
}

export function GetChannelConfigAsMap(arg1) {
  return window['go']['app']['App']['GetChannelConfigAsMap'](arg1);
}

export function GetChannelTemplates() {
  return window['go']['app']['App']['GetChannelTemplates']();
}

export function GetConversationChannel(arg1) {
  return window['go']['app']['App']['GetConversationChannel'](arg1);
}

export function GetMessagingStatus() {
  return window['go']['app']['App']['GetMessagingStatus']();
}

export function GetModelCatalogByProvider(arg1) {
  return window['go']['app']['App']['GetModelCatalogByProvider'](arg1);
}

export function GetModels() {
  return window['go']['app']['App']['GetModels']();
}

export function GetModelsByProvider(arg1) {
  return window['go']['app']['App']['GetModelsByProvider'](arg1);
}

export function GetVaultIntegrityStatus() {
  return window['go']['app']['App']['GetVaultIntegrityStatus']();
}

export function HasMasterKey() {
  return window['go']['app']['App']['HasMasterKey']();
}

export function ImportConversations(arg1) {
  return window['go']['app']['App']['ImportConversations'](arg1);
}

export function ImportData(arg1, arg2) {
  return window['go']['app']['App']['ImportData'](arg1, arg2);
}

export function ImportDataWithResolutions(arg1) {
  return window['go']['app']['App']['ImportDataWithResolutions'](arg1);
}

export function ImportWorkspace(arg1) {
  return window['go']['app']['App']['ImportWorkspace'](arg1);
}

export function ListWorkspaces() {
  return window['go']['app']['App']['ListWorkspaces']();
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['app']['App']['Logout'](arg1);
}

export function MoveWorkspaceTabTo(arg1, arg2) {
  return window['go']['app']['App']['MoveWorkspaceTabTo'](arg1, arg2);
}

export function RefreshAuth(arg1) {
  return window['go']['app']['App']['RefreshAuth'](arg1);
}

export function RefreshModelCatalogByProvider(arg1) {
  return window['go']['app']['App']['RefreshModelCatalogByProvider'](arg1);
}

export function RefreshModels() {
  return window['go']['app']['App']['RefreshModels']();
}

export function RefreshModelsByProvider(arg1) {
  return window['go']['app']['App']['RefreshModelsByProvider'](arg1);
}

export function RemoveAuthorizedContact(arg1, arg2) {
  return window['go']['app']['App']['RemoveAuthorizedContact'](arg1, arg2);
}

export function RemoveWorkspaceTab(arg1) {
  return window['go']['app']['App']['RemoveWorkspaceTab'](arg1);
}

export function RenameWorkspace(arg1) {
  return window['go']['app']['App']['RenameWorkspace'](arg1);
}

export function ReorderWorkspaceTabs(arg1) {
  return window['go']['app']['App']['ReorderWorkspaceTabs'](arg1);
}

export function RestartChannel(arg1) {
  return window['go']['app']['App']['RestartChannel'](arg1);
}

export function RetryMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['RetryMessage'](arg1, arg2, arg3);
}

export function RetryUserRuntimeInit() {
  return window['go']['app']['App']['RetryUserRuntimeInit']();
}

export function SaveChannelConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveChannelConfig'](arg1, arg2);
}

export function SaveWorkspace() {
  return window['go']['app']['App']['SaveWorkspace']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendMessageSync(arg1, arg2) {
  return window['go']['app']['App']['SendMessageSync'](arg1, arg2);
}

export function SetActiveWorkspaceTab(arg1) {
  return window['go']['app']['App']['SetActiveWorkspaceTab'](arg1);
}

export function SetWorkspaceProfile(arg1) {
  return window['go']['app']['App']['SetWorkspaceProfile'](arg1);
}

export function SetupMasterPassword(arg1) {
  return window['go']['app']['App']['SetupMasterPassword'](arg1);
}

export function SetupVault(arg1) {
  return window['go']['app']['App']['SetupVault'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function StartupWithAdapters(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StartupWithAdapters'](arg1, arg2, arg3, arg4);
}

export function SwitchWorkspace(arg1) {
  return window['go']['app']['App']['SwitchWorkspace'](arg1);
}

export function UnassignConversationFromChannel(arg1) {
  return window['go']['app']['App']['UnassignConversationFromChannel'](arg1);
}

export function UnlockVault(arg1, arg2) {
  return window['go']['app']['App']['UnlockVault'](arg1, arg2);
}

export function UpdateWorkspaceTab(arg1, arg2) {
  return window['go']['app']['App']['UpdateWorkspaceTab'](arg1, arg2);
}
