// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {portability} from '../models';
import {context} from '../models';
import {app} from '../models';
import {database} from '../models';
import {llm} from '../models';
import {credentials} from '../models';
import {ports} from '../models';

export function AnalyzeImportData(arg1:string,arg2:string):Promise<portability.ImportAnalysis>;

export function CanPersistCredentials():Promise<boolean>;

export function CancelStreamingForConversation(arg1:string):Promise<void>;

export function Context():Promise<context.Context>;

export function CreateAdminUser(arg1:app.CreateAdminRequest):Promise<database.User>;

export function ExportConversations(arg1:Array<string>):Promise<string>;

export function ExportConversationsToFile(arg1:Array<string>,arg2:string,arg3:portability.ContentExportOptions):Promise<string>;

export function ExportData(arg1:portability.ExportRequest):Promise<string>;

export function ExportDataToFile(arg1:portability.ExportRequest,arg2:string):Promise<string>;

export function GetAuthStatus():Promise<app.AuthStatus>;

export function GetAuthUser():Promise<app.AuthUser>;

export function GetModelCatalogByProvider(arg1:string):Promise<llm.ModelCatalog>;

export function GetModels():Promise<Array<string>>;

export function GetModelsByProvider(arg1:string):Promise<Array<string>>;

export function GetVaultIntegrityStatus():Promise<credentials.VaultIntegrityStatus>;

export function HasMasterKey():Promise<boolean>;

export function ImportConversations(arg1:string):Promise<portability.ImportResult>;

export function ImportData(arg1:string,arg2:string):Promise<portability.ImportResult>;

export function ImportDataWithResolutions(arg1:portability.ImportRequest):Promise<portability.ImportResult>;

export function Login(arg1:app.LoginRequest):Promise<app.AuthUser>;

export function Logout(arg1:app.LogoutRequest):Promise<void>;

export function RefreshAuth(arg1:app.RefreshRequest):Promise<app.AuthUser>;

export function RefreshModelCatalogByProvider(arg1:string):Promise<llm.ModelCatalog>;

export function RefreshModels():Promise<Array<string>>;

export function RefreshModelsByProvider(arg1:string):Promise<Array<string>>;

export function RetryMessage(arg1:string,arg2:string,arg3:llm.ChatParams):Promise<string>;

export function RetryUserRuntimeInit():Promise<app.RuntimePartialInitPayload>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:llm.ChatParams):Promise<string>;

export function SendMessageSync(arg1:Array<llm.Message>,arg2:llm.ChatParams):Promise<string>;

export function SetupMasterPassword(arg1:string):Promise<string>;

export function SetupVault(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function Shutdown():Promise<void>;

export function StartupWithAdapters(arg1:context.Context,arg2:ports.Emitter,arg3:ports.WindowPort,arg4:ports.SystemDialogPort):Promise<void>;

export function UnlockVault(arg1:string,arg2:string):Promise<void>;
