// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {portability} from '../models';
import {context} from '../models';
import {app} from '../models';
import {database} from '../models';
import {channels} from '../models';
import {contacts} from '../models';
import {controllers} from '../models';
import {llm} from '../models';
import {credentials} from '../models';
import {ports} from '../models';

export function AddWorkspaceTab(arg1:workspace.Tab):Promise<workspace.Workspace>;

export function AnalyzeImportData(arg1:string,arg2:string):Promise<portability.ImportAnalysis>;

export function AssignConversationToChannel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AuthorizeMessagingContactFull(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CanPersistCredentials():Promise<boolean>;

export function CancelStreamingForConversation(arg1:string):Promise<void>;

export function Context():Promise<context.Context>;

export function CreateAdminUser(arg1:app.CreateAdminRequest):Promise<database.User>;

export function CreateChannelFromTemplate(arg1:string,arg2:Record<string, any>):Promise<void>;

export function CreateWorkspace(arg1:string):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function EditorDeleteDraft(arg1:string):Promise<void>;

export function EditorGetDraftPath(arg1:string):Promise<string>;

export function EditorGetFileInfo(arg1:string):Promise<app.EditorFileInfo>;

export function EditorLoadState():Promise<app.EditorState>;

export function EditorOpenFile():Promise<app.EditorOpenResult>;

export function EditorReadDraft(arg1:string):Promise<string>;

export function EditorReadFile(arg1:string):Promise<string>;

export function EditorRenameFile(arg1:string,arg2:string):Promise<string>;

export function EditorSaveFileDialog(arg1:string):Promise<string>;

export function EditorSaveState(arg1:app.EditorState):Promise<void>;

export function EditorUnwatchFile(arg1:string):Promise<void>;

export function EditorWatchFile(arg1:string):Promise<void>;

export function EditorWriteDraft(arg1:string,arg2:string):Promise<void>;

export function EditorWriteFile(arg1:string,arg2:string):Promise<void>;

export function ExportConversations(arg1:Array<string>):Promise<string>;

export function ExportConversationsToFile(arg1:Array<string>,arg2:string,arg3:portability.ContentExportOptions):Promise<string>;

export function ExportData(arg1:portability.ExportRequest):Promise<string>;

export function ExportDataToFile(arg1:portability.ExportRequest,arg2:string):Promise<string>;

export function ExportWorkspace():Promise<string>;

export function GetActiveWorkspace():Promise<workspace.Workspace>;

export function GetAllChannelConfigs():Promise<Record<string, channels.ChannelConfig>>;

export function GetAuthStatus():Promise<app.AuthStatus>;

export function GetAuthUser():Promise<app.AuthUser>;

export function GetAuthorizedContacts():Promise<contacts.ContactsFile>;

export function GetAvailableChannels():Promise<Array<controllers.ChannelInfo>>;

export function GetChannelConfig(arg1:string):Promise<channels.ChannelConfig>;

export function GetChannelConfigAsMap(arg1:string):Promise<Record<string, any>>;

export function GetChannelTemplates():Promise<Array<channels.ChannelTemplate>>;

export function GetConversationChannel(arg1:string):Promise<string>;

export function GetMessagingStatus():Promise<Record<string, string>>;

export function GetModelCatalogByProvider(arg1:string):Promise<llm.ModelCatalog>;

export function GetModels():Promise<Array<string>>;

export function GetModelsByProvider(arg1:string):Promise<Array<string>>;

export function GetVaultIntegrityStatus():Promise<credentials.VaultIntegrityStatus>;

export function HasMasterKey():Promise<boolean>;

export function ImportConversations(arg1:string):Promise<portability.ImportResult>;

export function ImportData(arg1:string,arg2:string):Promise<portability.ImportResult>;

export function ImportDataWithResolutions(arg1:portability.ImportRequest):Promise<portability.ImportResult>;

export function ImportWorkspace(arg1:string):Promise<workspace.Workspace>;

export function ListWorkspaces():Promise<Array<workspace.WorkspaceInfo>>;

export function Login(arg1:app.LoginRequest):Promise<app.AuthUser>;

export function Logout(arg1:app.LogoutRequest):Promise<void>;

export function MoveWorkspaceTabTo(arg1:string,arg2:string):Promise<workspace.Workspace>;

export function RefreshAuth(arg1:app.RefreshRequest):Promise<app.AuthUser>;

export function RefreshModelCatalogByProvider(arg1:string):Promise<llm.ModelCatalog>;

export function RefreshModels():Promise<Array<string>>;

export function RefreshModelsByProvider(arg1:string):Promise<Array<string>>;

export function RemoveAuthorizedContact(arg1:string,arg2:string):Promise<void>;

export function RemoveWorkspaceTab(arg1:string):Promise<workspace.Workspace>;

export function RenameWorkspace(arg1:string):Promise<void>;

export function ReorderWorkspaceTabs(arg1:Array<string>):Promise<void>;

export function RestartChannel(arg1:string):Promise<void>;

export function RetryMessage(arg1:string,arg2:string,arg3:llm.ChatParams):Promise<string>;

export function RetryUserRuntimeInit():Promise<app.RuntimePartialInitPayload>;

export function SaveChannelConfig(arg1:string,arg2:channels.ChannelConfig):Promise<void>;

export function SaveWorkspace():Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:llm.ChatParams):Promise<string>;

export function SendMessageSync(arg1:Array<llm.Message>,arg2:llm.ChatParams):Promise<string>;

export function SetActiveWorkspaceTab(arg1:string):Promise<void>;

export function SetWorkspaceProfile(arg1:string):Promise<void>;

export function SetupMasterPassword(arg1:string):Promise<string>;

export function SetupVault(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function Shutdown():Promise<void>;

export function StartupWithAdapters(arg1:context.Context,arg2:ports.Emitter,arg3:ports.WindowPort,arg4:ports.SystemDialogPort):Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<workspace.Workspace>;

export function UnassignConversationFromChannel(arg1:string):Promise<void>;

export function UnlockVault(arg1:string,arg2:string):Promise<void>;

export function UpdateWorkspaceTab(arg1:string,arg2:Record<string, any>):Promise<void>;
