// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChildMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AddChildMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function AddMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddMessage'](arg1, arg2, arg3);
}

export function AddMessageWithMedia(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddMessageWithMedia'](arg1, arg2, arg3, arg4);
}

export function AddMessageWithTokens(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['AddMessageWithTokens'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddMessageWithTokensAndMedia(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['AddMessageWithTokensAndMedia'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddWorkspaceTab(arg1) {
  return window['go']['app']['App']['AddWorkspaceTab'](arg1);
}

export function AnalyzeImportData(arg1, arg2) {
  return window['go']['app']['App']['AnalyzeImportData'](arg1, arg2);
}

export function AssignConversationToChannel(arg1, arg2, arg3) {
  return window['go']['app']['App']['AssignConversationToChannel'](arg1, arg2, arg3);
}

export function AuthorizeMessagingContactFull(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AuthorizeMessagingContactFull'](arg1, arg2, arg3, arg4);
}

export function CanPersistCredentials() {
  return window['go']['app']['App']['CanPersistCredentials']();
}

export function CancelStreamingForConversation(arg1) {
  return window['go']['app']['App']['CancelStreamingForConversation'](arg1);
}

export function ClearConversation(arg1) {
  return window['go']['app']['App']['ClearConversation'](arg1);
}

export function ClearTaskList(arg1) {
  return window['go']['app']['App']['ClearTaskList'](arg1);
}

export function CloneTaskList(arg1, arg2) {
  return window['go']['app']['App']['CloneTaskList'](arg1, arg2);
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function CreateAdminUser(arg1) {
  return window['go']['app']['App']['CreateAdminUser'](arg1);
}

export function CreateChannelFromTemplate(arg1, arg2) {
  return window['go']['app']['App']['CreateChannelFromTemplate'](arg1, arg2);
}

export function CreateConversation(arg1, arg2) {
  return window['go']['app']['App']['CreateConversation'](arg1, arg2);
}

export function CreateMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateMessage'](arg1, arg2, arg3);
}

export function CreateTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['CreateTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTaskList(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateTaskList'](arg1, arg2, arg3);
}

export function CreateTaskNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CreateTaskNote'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateWorkspace(arg1) {
  return window['go']['app']['App']['CreateWorkspace'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['app']['App']['DeleteConversation'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['app']['App']['DeleteMessage'](arg1);
}

export function DeleteMessages(arg1, arg2) {
  return window['go']['app']['App']['DeleteMessages'](arg1, arg2);
}

export function DeleteTask(arg1) {
  return window['go']['app']['App']['DeleteTask'](arg1);
}

export function DeleteTaskList(arg1) {
  return window['go']['app']['App']['DeleteTaskList'](arg1);
}

export function DeleteTaskNote(arg1) {
  return window['go']['app']['App']['DeleteTaskNote'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['app']['App']['DeleteWorkspace'](arg1);
}

export function DemoteTask(arg1, arg2) {
  return window['go']['app']['App']['DemoteTask'](arg1, arg2);
}

export function DispatchSpeech(arg1) {
  return window['go']['app']['App']['DispatchSpeech'](arg1);
}

export function EditorDeleteDraft(arg1) {
  return window['go']['app']['App']['EditorDeleteDraft'](arg1);
}

export function EditorGetDraftPath(arg1) {
  return window['go']['app']['App']['EditorGetDraftPath'](arg1);
}

export function EditorGetFileInfo(arg1) {
  return window['go']['app']['App']['EditorGetFileInfo'](arg1);
}

export function EditorLoadState() {
  return window['go']['app']['App']['EditorLoadState']();
}

export function EditorOpenFile() {
  return window['go']['app']['App']['EditorOpenFile']();
}

export function EditorReadDraft(arg1) {
  return window['go']['app']['App']['EditorReadDraft'](arg1);
}

export function EditorReadFile(arg1) {
  return window['go']['app']['App']['EditorReadFile'](arg1);
}

export function EditorRenameFile(arg1, arg2) {
  return window['go']['app']['App']['EditorRenameFile'](arg1, arg2);
}

export function EditorSaveFileDialog(arg1) {
  return window['go']['app']['App']['EditorSaveFileDialog'](arg1);
}

export function EditorSaveState(arg1) {
  return window['go']['app']['App']['EditorSaveState'](arg1);
}

export function EditorUnwatchFile(arg1) {
  return window['go']['app']['App']['EditorUnwatchFile'](arg1);
}

export function EditorWatchFile(arg1) {
  return window['go']['app']['App']['EditorWatchFile'](arg1);
}

export function EditorWriteDraft(arg1, arg2) {
  return window['go']['app']['App']['EditorWriteDraft'](arg1, arg2);
}

export function EditorWriteFile(arg1, arg2) {
  return window['go']['app']['App']['EditorWriteFile'](arg1, arg2);
}

export function EnsureConversation(arg1) {
  return window['go']['app']['App']['EnsureConversation'](arg1);
}

export function ExportConversations(arg1) {
  return window['go']['app']['App']['ExportConversations'](arg1);
}

export function ExportConversationsToFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportConversationsToFile'](arg1, arg2, arg3);
}

export function ExportData(arg1) {
  return window['go']['app']['App']['ExportData'](arg1);
}

export function ExportDataToFile(arg1, arg2) {
  return window['go']['app']['App']['ExportDataToFile'](arg1, arg2);
}

export function ExportWorkspace() {
  return window['go']['app']['App']['ExportWorkspace']();
}

export function GenerateAndSaveMessageAudio(arg1, arg2) {
  return window['go']['app']['App']['GenerateAndSaveMessageAudio'](arg1, arg2);
}

export function GetActiveWorkspace() {
  return window['go']['app']['App']['GetActiveWorkspace']();
}

export function GetAgentPermissions() {
  return window['go']['app']['App']['GetAgentPermissions']();
}

export function GetAgentSessionOptions(arg1) {
  return window['go']['app']['App']['GetAgentSessionOptions'](arg1);
}

export function GetAllChannelConfigs() {
  return window['go']['app']['App']['GetAllChannelConfigs']();
}

export function GetAllTaskLists() {
  return window['go']['app']['App']['GetAllTaskLists']();
}

export function GetAllTokenStats() {
  return window['go']['app']['App']['GetAllTokenStats']();
}

export function GetAuthStatus() {
  return window['go']['app']['App']['GetAuthStatus']();
}

export function GetAuthUser() {
  return window['go']['app']['App']['GetAuthUser']();
}

export function GetAuthorizedContacts() {
  return window['go']['app']['App']['GetAuthorizedContacts']();
}

export function GetAvailableChannels() {
  return window['go']['app']['App']['GetAvailableChannels']();
}

export function GetChannelConfig(arg1) {
  return window['go']['app']['App']['GetChannelConfig'](arg1);
}

export function GetChannelConfigAsMap(arg1) {
  return window['go']['app']['App']['GetChannelConfigAsMap'](arg1);
}

export function GetChannelTemplates() {
  return window['go']['app']['App']['GetChannelTemplates']();
}

export function GetConversation(arg1) {
  return window['go']['app']['App']['GetConversation'](arg1);
}

export function GetConversationChannel(arg1) {
  return window['go']['app']['App']['GetConversationChannel'](arg1);
}

export function GetConversationInfo(arg1) {
  return window['go']['app']['App']['GetConversationInfo'](arg1);
}

export function GetConversationMessageWindow(arg1) {
  return window['go']['app']['App']['GetConversationMessageWindow'](arg1);
}

export function GetConversationSummary(arg1) {
  return window['go']['app']['App']['GetConversationSummary'](arg1);
}

export function GetConversationWithThreads(arg1) {
  return window['go']['app']['App']['GetConversationWithThreads'](arg1);
}

export function GetConversations() {
  return window['go']['app']['App']['GetConversations']();
}

export function GetConversationsByIDs(arg1) {
  return window['go']['app']['App']['GetConversationsByIDs'](arg1);
}

export function GetConversationsPage(arg1, arg2) {
  return window['go']['app']['App']['GetConversationsPage'](arg1, arg2);
}

export function GetEffectiveModel() {
  return window['go']['app']['App']['GetEffectiveModel']();
}

export function GetMessageAudio(arg1) {
  return window['go']['app']['App']['GetMessageAudio'](arg1);
}

export function GetMessageChildren(arg1) {
  return window['go']['app']['App']['GetMessageChildren'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['app']['App']['GetMessages'](arg1, arg2);
}

export function GetMessagesBefore(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetMessagesBefore'](arg1, arg2, arg3);
}

export function GetMessagingStatus() {
  return window['go']['app']['App']['GetMessagingStatus']();
}

export function GetModelCatalogByProvider(arg1) {
  return window['go']['app']['App']['GetModelCatalogByProvider'](arg1);
}

export function GetModels() {
  return window['go']['app']['App']['GetModels']();
}

export function GetModelsByProvider(arg1) {
  return window['go']['app']['App']['GetModelsByProvider'](arg1);
}

export function GetOpenAITTSVoices() {
  return window['go']['app']['App']['GetOpenAITTSVoices']();
}

export function GetRecentMessages(arg1, arg2) {
  return window['go']['app']['App']['GetRecentMessages'](arg1, arg2);
}

export function GetSTTModels(arg1) {
  return window['go']['app']['App']['GetSTTModels'](arg1);
}

export function GetSpeechProviders() {
  return window['go']['app']['App']['GetSpeechProviders']();
}

export function GetSubtasks(arg1) {
  return window['go']['app']['App']['GetSubtasks'](arg1);
}

export function GetTTSModels(arg1) {
  return window['go']['app']['App']['GetTTSModels'](arg1);
}

export function GetTTSVoices(arg1, arg2) {
  return window['go']['app']['App']['GetTTSVoices'](arg1, arg2);
}

export function GetTask(arg1) {
  return window['go']['app']['App']['GetTask'](arg1);
}

export function GetTaskCountsByStatus(arg1) {
  return window['go']['app']['App']['GetTaskCountsByStatus'](arg1);
}

export function GetTaskList(arg1) {
  return window['go']['app']['App']['GetTaskList'](arg1);
}

export function GetTaskListStats(arg1) {
  return window['go']['app']['App']['GetTaskListStats'](arg1);
}

export function GetTaskListWithHierarchy(arg1) {
  return window['go']['app']['App']['GetTaskListWithHierarchy'](arg1);
}

export function GetTaskListsByConversation(arg1) {
  return window['go']['app']['App']['GetTaskListsByConversation'](arg1);
}

export function GetTaskNotes(arg1) {
  return window['go']['app']['App']['GetTaskNotes'](arg1);
}

export function GetTasksByConversation(arg1) {
  return window['go']['app']['App']['GetTasksByConversation'](arg1);
}

export function GetTasksByStatus(arg1, arg2) {
  return window['go']['app']['App']['GetTasksByStatus'](arg1, arg2);
}

export function GetTasksByTaskListID(arg1) {
  return window['go']['app']['App']['GetTasksByTaskListID'](arg1);
}

export function GetVaultIntegrityStatus() {
  return window['go']['app']['App']['GetVaultIntegrityStatus']();
}

export function GetWorkflow(arg1) {
  return window['go']['app']['App']['GetWorkflow'](arg1);
}

export function HasMasterKey() {
  return window['go']['app']['App']['HasMasterKey']();
}

export function ImportConversations(arg1) {
  return window['go']['app']['App']['ImportConversations'](arg1);
}

export function ImportData(arg1, arg2) {
  return window['go']['app']['App']['ImportData'](arg1, arg2);
}

export function ImportDataWithResolutions(arg1) {
  return window['go']['app']['App']['ImportDataWithResolutions'](arg1);
}

export function ImportWorkspace(arg1) {
  return window['go']['app']['App']['ImportWorkspace'](arg1);
}

export function InitSpeechManagerFromProfile() {
  return window['go']['app']['App']['InitSpeechManagerFromProfile']();
}

export function ListWorkspaces() {
  return window['go']['app']['App']['ListWorkspaces']();
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['app']['App']['Logout'](arg1);
}

export function MoveWorkspaceTabTo(arg1, arg2) {
  return window['go']['app']['App']['MoveWorkspaceTabTo'](arg1, arg2);
}

export function PromoteTask(arg1) {
  return window['go']['app']['App']['PromoteTask'](arg1);
}

export function RebuildSearchIndex() {
  return window['go']['app']['App']['RebuildSearchIndex']();
}

export function RefreshAuth(arg1) {
  return window['go']['app']['App']['RefreshAuth'](arg1);
}

export function RefreshModelCatalogByProvider(arg1) {
  return window['go']['app']['App']['RefreshModelCatalogByProvider'](arg1);
}

export function RefreshModels() {
  return window['go']['app']['App']['RefreshModels']();
}

export function RefreshModelsByProvider(arg1) {
  return window['go']['app']['App']['RefreshModelsByProvider'](arg1);
}

export function RemoveAuthorizedContact(arg1, arg2) {
  return window['go']['app']['App']['RemoveAuthorizedContact'](arg1, arg2);
}

export function RemoveWorkspaceTab(arg1) {
  return window['go']['app']['App']['RemoveWorkspaceTab'](arg1);
}

export function RenameConversation(arg1, arg2) {
  return window['go']['app']['App']['RenameConversation'](arg1, arg2);
}

export function RenameWorkspace(arg1) {
  return window['go']['app']['App']['RenameWorkspace'](arg1);
}

export function ReorderTasks(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReorderTasks'](arg1, arg2, arg3);
}

export function ReorderWorkflowStatuses(arg1, arg2) {
  return window['go']['app']['App']['ReorderWorkflowStatuses'](arg1, arg2);
}

export function ReorderWorkspaceTabs(arg1) {
  return window['go']['app']['App']['ReorderWorkspaceTabs'](arg1);
}

export function RestartChannel(arg1) {
  return window['go']['app']['App']['RestartChannel'](arg1);
}

export function RetryMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['RetryMessage'](arg1, arg2, arg3);
}

export function RetryUserRuntimeInit() {
  return window['go']['app']['App']['RetryUserRuntimeInit']();
}

export function RevokeAgentPermission(arg1, arg2) {
  return window['go']['app']['App']['RevokeAgentPermission'](arg1, arg2);
}

export function SaveChannelConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveChannelConfig'](arg1, arg2);
}

export function SaveMessageAudio(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveMessageAudio'](arg1, arg2, arg3);
}

export function SaveWorkspace() {
  return window['go']['app']['App']['SaveWorkspace']();
}

export function SearchConversationHistory(arg1, arg2) {
  return window['go']['app']['App']['SearchConversationHistory'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendMessageSync(arg1, arg2) {
  return window['go']['app']['App']['SendMessageSync'](arg1, arg2);
}

export function SetActiveWorkspaceTab(arg1) {
  return window['go']['app']['App']['SetActiveWorkspaceTab'](arg1);
}

export function SetAgentSessionOption(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetAgentSessionOption'](arg1, arg2, arg3);
}

export function SetConversationModel(arg1, arg2) {
  return window['go']['app']['App']['SetConversationModel'](arg1, arg2);
}

export function SetOpenAITTSSpeed(arg1) {
  return window['go']['app']['App']['SetOpenAITTSSpeed'](arg1);
}

export function SetOpenAITTSVoice(arg1) {
  return window['go']['app']['App']['SetOpenAITTSVoice'](arg1);
}

export function SetTaskConversation(arg1, arg2) {
  return window['go']['app']['App']['SetTaskConversation'](arg1, arg2);
}

export function SetTaskListConversation(arg1, arg2) {
  return window['go']['app']['App']['SetTaskListConversation'](arg1, arg2);
}

export function SetTaskListViewMode(arg1, arg2) {
  return window['go']['app']['App']['SetTaskListViewMode'](arg1, arg2);
}

export function SetWorkspaceProfile(arg1) {
  return window['go']['app']['App']['SetWorkspaceProfile'](arg1);
}

export function SetupMasterPassword(arg1) {
  return window['go']['app']['App']['SetupMasterPassword'](arg1);
}

export function SetupVault(arg1) {
  return window['go']['app']['App']['SetupVault'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function SpeakMessage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['SpeakMessage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SpeakPreview(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['SpeakPreview'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function StartupWithAdapters(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StartupWithAdapters'](arg1, arg2, arg3, arg4);
}

export function SwitchWorkspace(arg1) {
  return window['go']['app']['App']['SwitchWorkspace'](arg1);
}

export function SynthesizeOpenAI(arg1) {
  return window['go']['app']['App']['SynthesizeOpenAI'](arg1);
}

export function SynthesizeOpenAIStream(arg1, arg2, arg3) {
  return window['go']['app']['App']['SynthesizeOpenAIStream'](arg1, arg2, arg3);
}

export function SynthesizeOpenAIWithVoice(arg1, arg2) {
  return window['go']['app']['App']['SynthesizeOpenAIWithVoice'](arg1, arg2);
}

export function TranscribeWhisper(arg1, arg2) {
  return window['go']['app']['App']['TranscribeWhisper'](arg1, arg2);
}

export function UnassignConversationFromChannel(arg1) {
  return window['go']['app']['App']['UnassignConversationFromChannel'](arg1);
}

export function UnlockVault(arg1, arg2) {
  return window['go']['app']['App']['UnlockVault'](arg1, arg2);
}

export function UpdateConversation(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateConversation'](arg1, arg2, arg3);
}

export function UpdateConversationModel(arg1, arg2) {
  return window['go']['app']['App']['UpdateConversationModel'](arg1, arg2);
}

export function UpdateMessage(arg1, arg2) {
  return window['go']['app']['App']['UpdateMessage'](arg1, arg2);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTaskAssignee(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateTaskAssignee'](arg1, arg2, arg3);
}

export function UpdateTaskFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['App']['UpdateTaskFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateTaskList(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateTaskList'](arg1, arg2, arg3);
}

export function UpdateTaskNote(arg1, arg2) {
  return window['go']['app']['App']['UpdateTaskNote'](arg1, arg2);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['app']['App']['UpdateTaskStatus'](arg1, arg2);
}

export function UpdateWorkflow(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateWorkflow'](arg1, arg2, arg3);
}

export function UpdateWorkflowFull(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateWorkflowFull'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateWorkspaceTab(arg1, arg2) {
  return window['go']['app']['App']['UpdateWorkspaceTab'](arg1, arg2);
}

export function ValidateStatusTransition(arg1, arg2, arg3) {
  return window['go']['app']['App']['ValidateStatusTransition'](arg1, arg2, arg3);
}
