// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CanPersistCredentials() {
  return window['go']['app']['App']['CanPersistCredentials']();
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function CreateAdminUser(arg1) {
  return window['go']['app']['App']['CreateAdminUser'](arg1);
}

export function GetAuthStatus() {
  return window['go']['app']['App']['GetAuthStatus']();
}

export function GetAuthUser() {
  return window['go']['app']['App']['GetAuthUser']();
}

export function GetVaultIntegrityStatus() {
  return window['go']['app']['App']['GetVaultIntegrityStatus']();
}

export function HasMasterKey() {
  return window['go']['app']['App']['HasMasterKey']();
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['app']['App']['Logout'](arg1);
}

export function RefreshAuth(arg1) {
  return window['go']['app']['App']['RefreshAuth'](arg1);
}

export function RetryUserRuntimeInit() {
  return window['go']['app']['App']['RetryUserRuntimeInit']();
}

export function SetupMasterPassword(arg1) {
  return window['go']['app']['App']['SetupMasterPassword'](arg1);
}

export function SetupVault(arg1) {
  return window['go']['app']['App']['SetupVault'](arg1);
}

export function SetWakeLock(arg1) {
  return window['go']['app']['App']['SetWakeLock'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function StartupWithAdapters(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StartupWithAdapters'](arg1, arg2, arg3, arg4);
}

export function UnlockVault(arg1, arg2) {
  return window['go']['app']['App']['UnlockVault'](arg1, arg2);
}
