// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChildMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddChildMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function AddMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMessage'](arg1, arg2, arg3);
}

export function AddMessageWithMedia(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddMessageWithMedia'](arg1, arg2, arg3, arg4);
}

export function AddMessageWithTokens(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddMessageWithTokens'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddMessageWithTokensAndMedia(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddMessageWithTokensAndMedia'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ClearConversation(arg1) {
  return window['go']['main']['App']['ClearConversation'](arg1);
}

export function ClearConversationChatProfile(arg1) {
  return window['go']['main']['App']['ClearConversationChatProfile'](arg1);
}

export function ClearTab(arg1) {
  return window['go']['main']['App']['ClearTab'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function CreateChatProfile(arg1) {
  return window['go']['main']['App']['CreateChatProfile'](arg1);
}

export function CreateConversation(arg1, arg2) {
  return window['go']['main']['App']['CreateConversation'](arg1, arg2);
}

export function CreateInteractionProfile(arg1) {
  return window['go']['main']['App']['CreateInteractionProfile'](arg1);
}

export function CreateInteractionTrigger(arg1) {
  return window['go']['main']['App']['CreateInteractionTrigger'](arg1);
}

export function CreateMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMessage'](arg1, arg2, arg3);
}

export function CreateNewConversation(arg1) {
  return window['go']['main']['App']['CreateNewConversation'](arg1);
}

export function CreateTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTab'](arg1, arg2, arg3);
}

export function CreateVoiceProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateVoiceProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateVoiceProfileFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateVoiceProfileFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function DeleteChatProfile(arg1) {
  return window['go']['main']['App']['DeleteChatProfile'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteInteractionProfile(arg1) {
  return window['go']['main']['App']['DeleteInteractionProfile'](arg1);
}

export function DeleteInteractionTrigger(arg1) {
  return window['go']['main']['App']['DeleteInteractionTrigger'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function DeleteMessages(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessages'](arg1, arg2);
}

export function DeleteVoiceProfile(arg1) {
  return window['go']['main']['App']['DeleteVoiceProfile'](arg1);
}

export function DisableVoiceHotkey() {
  return window['go']['main']['App']['DisableVoiceHotkey']();
}

export function EnableVoiceHotkey() {
  return window['go']['main']['App']['EnableVoiceHotkey']();
}

export function ExportConversations(arg1) {
  return window['go']['main']['App']['ExportConversations'](arg1);
}

export function ExportInteractionProfiles(arg1) {
  return window['go']['main']['App']['ExportInteractionProfiles'](arg1);
}

export function ExportVoiceProfiles(arg1) {
  return window['go']['main']['App']['ExportVoiceProfiles'](arg1);
}

export function GetActiveInteractionProfile() {
  return window['go']['main']['App']['GetActiveInteractionProfile']();
}

export function GetActiveProfileHotkeys(arg1) {
  return window['go']['main']['App']['GetActiveProfileHotkeys'](arg1);
}

export function GetActiveTab() {
  return window['go']['main']['App']['GetActiveTab']();
}

export function GetAllTabs() {
  return window['go']['main']['App']['GetAllTabs']();
}

export function GetAllTokenStats() {
  return window['go']['main']['App']['GetAllTokenStats']();
}

export function GetAllVoiceProfiles() {
  return window['go']['main']['App']['GetAllVoiceProfiles']();
}

export function GetChatProfile(arg1) {
  return window['go']['main']['App']['GetChatProfile'](arg1);
}

export function GetChatProfiles() {
  return window['go']['main']['App']['GetChatProfiles']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversationInfo(arg1) {
  return window['go']['main']['App']['GetConversationInfo'](arg1);
}

export function GetConversationModel(arg1) {
  return window['go']['main']['App']['GetConversationModel'](arg1);
}

export function GetConversationPreferences(arg1) {
  return window['go']['main']['App']['GetConversationPreferences'](arg1);
}

export function GetConversationTokenStats(arg1) {
  return window['go']['main']['App']['GetConversationTokenStats'](arg1);
}

export function GetConversationWithThreads(arg1) {
  return window['go']['main']['App']['GetConversationWithThreads'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetCurrentConversationID() {
  return window['go']['main']['App']['GetCurrentConversationID']();
}

export function GetCurrentTabID() {
  return window['go']['main']['App']['GetCurrentTabID']();
}

export function GetDefaultChatProfile() {
  return window['go']['main']['App']['GetDefaultChatProfile']();
}

export function GetDefaultInteractionProfile() {
  return window['go']['main']['App']['GetDefaultInteractionProfile']();
}

export function GetDefaultVoiceProfile() {
  return window['go']['main']['App']['GetDefaultVoiceProfile']();
}

export function GetEffectiveChatProfile(arg1) {
  return window['go']['main']['App']['GetEffectiveChatProfile'](arg1);
}

export function GetEffectiveModel(arg1) {
  return window['go']['main']['App']['GetEffectiveModel'](arg1);
}

export function GetEffectiveVoiceProfile(arg1) {
  return window['go']['main']['App']['GetEffectiveVoiceProfile'](arg1);
}

export function GetGlobalHotkeys() {
  return window['go']['main']['App']['GetGlobalHotkeys']();
}

export function GetInteractionProfile(arg1) {
  return window['go']['main']['App']['GetInteractionProfile'](arg1);
}

export function GetInteractionProfiles() {
  return window['go']['main']['App']['GetInteractionProfiles']();
}

export function GetInteractionTrigger(arg1) {
  return window['go']['main']['App']['GetInteractionTrigger'](arg1);
}

export function GetMessageChildren(arg1) {
  return window['go']['main']['App']['GetMessageChildren'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetOpenAITTSVoices() {
  return window['go']['main']['App']['GetOpenAITTSVoices']();
}

export function GetSAPI5Voices() {
  return window['go']['main']['App']['GetSAPI5Voices']();
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function GetTriggersByProfile(arg1) {
  return window['go']['main']['App']['GetTriggersByProfile'](arg1);
}

export function GetVoiceProfile(arg1) {
  return window['go']['main']['App']['GetVoiceProfile'](arg1);
}

export function GetVoiceProfileByName(arg1) {
  return window['go']['main']['App']['GetVoiceProfileByName'](arg1);
}

export function ImportConversations(arg1) {
  return window['go']['main']['App']['ImportConversations'](arg1);
}

export function ImportInteractionProfiles(arg1) {
  return window['go']['main']['App']['ImportInteractionProfiles'](arg1);
}

export function ImportVoiceProfiles(arg1) {
  return window['go']['main']['App']['ImportVoiceProfiles'](arg1);
}

export function InitSpeechManager(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InitSpeechManager'](arg1, arg2, arg3, arg4, arg5);
}

export function IsGlobalHotkeySupported() {
  return window['go']['main']['App']['IsGlobalHotkeySupported']();
}

export function IsSAPI5Speaking() {
  return window['go']['main']['App']['IsSAPI5Speaking']();
}

export function LoadConversationInTab(arg1, arg2) {
  return window['go']['main']['App']['LoadConversationInTab'](arg1, arg2);
}

export function OpenConversationInCurrentTab(arg1) {
  return window['go']['main']['App']['OpenConversationInCurrentTab'](arg1);
}

export function OpenConversationInNewTab(arg1) {
  return window['go']['main']['App']['OpenConversationInNewTab'](arg1);
}

export function PreviewVoiceProfile(arg1, arg2) {
  return window['go']['main']['App']['PreviewVoiceProfile'](arg1, arg2);
}

export function PreviewVoiceSettings(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PreviewVoiceSettings'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RegisterInteractionProfileHotkeys(arg1) {
  return window['go']['main']['App']['RegisterInteractionProfileHotkeys'](arg1);
}

export function ReloadLLMClient() {
  return window['go']['main']['App']['ReloadLLMClient']();
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function RenameTab(arg1, arg2) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2);
}

export function ReorderTabs(arg1) {
  return window['go']['main']['App']['ReorderTabs'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchInteractionProfiles(arg1) {
  return window['go']['main']['App']['SearchInteractionProfiles'](arg1);
}

export function SearchVoiceProfiles(arg1) {
  return window['go']['main']['App']['SearchVoiceProfiles'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendMessageSync(arg1, arg2) {
  return window['go']['main']['App']['SendMessageSync'](arg1, arg2);
}

export function SetActiveInteractionProfile(arg1) {
  return window['go']['main']['App']['SetActiveInteractionProfile'](arg1);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function SetChatModel(arg1) {
  return window['go']['main']['App']['SetChatModel'](arg1);
}

export function SetConversationChatProfile(arg1, arg2) {
  return window['go']['main']['App']['SetConversationChatProfile'](arg1, arg2);
}

export function SetConversationModel(arg1, arg2) {
  return window['go']['main']['App']['SetConversationModel'](arg1, arg2);
}

export function SetConversationVoiceProfile(arg1, arg2) {
  return window['go']['main']['App']['SetConversationVoiceProfile'](arg1, arg2);
}

export function SetDefaultChatProfile(arg1) {
  return window['go']['main']['App']['SetDefaultChatProfile'](arg1);
}

export function SetDefaultInteractionProfile(arg1) {
  return window['go']['main']['App']['SetDefaultInteractionProfile'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetDefaultVoiceProfile(arg1) {
  return window['go']['main']['App']['SetDefaultVoiceProfile'](arg1);
}

export function SetOpenAITTSSpeed(arg1) {
  return window['go']['main']['App']['SetOpenAITTSSpeed'](arg1);
}

export function SetOpenAITTSVoice(arg1) {
  return window['go']['main']['App']['SetOpenAITTSVoice'](arg1);
}

export function SetSAPI5Rate(arg1) {
  return window['go']['main']['App']['SetSAPI5Rate'](arg1);
}

export function SetSAPI5Volume(arg1) {
  return window['go']['main']['App']['SetSAPI5Volume'](arg1);
}

export function SetVoiceHotkey(arg1, arg2) {
  return window['go']['main']['App']['SetVoiceHotkey'](arg1, arg2);
}

export function SpeakSAPI5(arg1, arg2) {
  return window['go']['main']['App']['SpeakSAPI5'](arg1, arg2);
}

export function StopSAPI5() {
  return window['go']['main']['App']['StopSAPI5']();
}

export function SwitchToTab(arg1) {
  return window['go']['main']['App']['SwitchToTab'](arg1);
}

export function SynthesizeOpenAI(arg1) {
  return window['go']['main']['App']['SynthesizeOpenAI'](arg1);
}

export function SynthesizeOpenAIStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['SynthesizeOpenAIStream'](arg1, arg2, arg3);
}

export function SynthesizeOpenAIWithVoice(arg1, arg2) {
  return window['go']['main']['App']['SynthesizeOpenAIWithVoice'](arg1, arg2);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function TestConnectionWithModels() {
  return window['go']['main']['App']['TestConnectionWithModels']();
}

export function TranscribeWhisper(arg1, arg2) {
  return window['go']['main']['App']['TranscribeWhisper'](arg1, arg2);
}

export function UnregisterInteractionProfileHotkeys(arg1) {
  return window['go']['main']['App']['UnregisterInteractionProfileHotkeys'](arg1);
}

export function UpdateChatProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatProfile'](arg1, arg2);
}

export function UpdateConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConversation'](arg1, arg2, arg3);
}

export function UpdateConversationModel(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationModel'](arg1, arg2);
}

export function UpdateConversationPreferences(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationPreferences'](arg1, arg2);
}

export function UpdateInteractionProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateInteractionProfile'](arg1, arg2);
}

export function UpdateInteractionTrigger(arg1, arg2) {
  return window['go']['main']['App']['UpdateInteractionTrigger'](arg1, arg2);
}

export function UpdateMessage(arg1, arg2) {
  return window['go']['main']['App']['UpdateMessage'](arg1, arg2);
}

export function UpdateTabTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTabTitle'](arg1, arg2);
}

export function UpdateVoiceProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateVoiceProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateVoiceProfileFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['UpdateVoiceProfileFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}
