// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function AddMessageWithMedia(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddMessageWithMedia'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddMessageWithTokens(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['AddMessageWithTokens'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function AddMessageWithTokensAndMedia(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['AddMessageWithTokensAndMedia'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function ClearConversation(arg1) {
  return window['go']['main']['App']['ClearConversation'](arg1);
}

export function ClearConversationChatProfile(arg1) {
  return window['go']['main']['App']['ClearConversationChatProfile'](arg1);
}

export function ClearTab(arg1) {
  return window['go']['main']['App']['ClearTab'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function CompleteOAuthFlow(arg1, arg2) {
  return window['go']['main']['App']['CompleteOAuthFlow'](arg1, arg2);
}

export function ConnectMCPAgent(arg1) {
  return window['go']['main']['App']['ConnectMCPAgent'](arg1);
}

export function CreateAgentConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateAgentConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateChatProfile(arg1) {
  return window['go']['main']['App']['CreateChatProfile'](arg1);
}

export function CreateConversation(arg1, arg2) {
  return window['go']['main']['App']['CreateConversation'](arg1, arg2);
}

export function CreateFAQ(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFAQ'](arg1, arg2, arg3);
}

export function CreateFileAgentAuthorizedPath(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFileAgentAuthorizedPath'](arg1, arg2, arg3, arg4);
}

export function CreateHTTPAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateHTTPAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateHTTPAgentFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['CreateHTTPAgentFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function CreateHTTPEndpoint(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateHTTPEndpoint'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreateInteractionProfile(arg1) {
  return window['go']['main']['App']['CreateInteractionProfile'](arg1);
}

export function CreateInteractionTrigger(arg1) {
  return window['go']['main']['App']['CreateInteractionTrigger'](arg1);
}

export function CreateMCPAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['CreateMCPAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function CreateMCPAgentFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17) {
  return window['go']['main']['App']['CreateMCPAgentFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
}

export function CreateMCPMessage(arg1, arg2) {
  return window['go']['main']['App']['CreateMCPMessage'](arg1, arg2);
}

export function CreateMemory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMemory'](arg1, arg2, arg3);
}

export function CreateNewConversation(arg1) {
  return window['go']['main']['App']['CreateNewConversation'](arg1);
}

export function CreateOAuthConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateOAuthConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreateTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTab'](arg1, arg2, arg3);
}

export function CreateVoiceProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateVoiceProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateVoiceProfileFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateVoiceProfileFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function DeleteAgentConfig(arg1) {
  return window['go']['main']['App']['DeleteAgentConfig'](arg1);
}

export function DeleteChatProfile(arg1) {
  return window['go']['main']['App']['DeleteChatProfile'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteFAQ(arg1) {
  return window['go']['main']['App']['DeleteFAQ'](arg1);
}

export function DeleteFileAgentAuthorizedPath(arg1) {
  return window['go']['main']['App']['DeleteFileAgentAuthorizedPath'](arg1);
}

export function DeleteHTTPAgent(arg1) {
  return window['go']['main']['App']['DeleteHTTPAgent'](arg1);
}

export function DeleteHTTPAgentFull(arg1) {
  return window['go']['main']['App']['DeleteHTTPAgentFull'](arg1);
}

export function DeleteHTTPEndpoint(arg1) {
  return window['go']['main']['App']['DeleteHTTPEndpoint'](arg1);
}

export function DeleteInteractionProfile(arg1) {
  return window['go']['main']['App']['DeleteInteractionProfile'](arg1);
}

export function DeleteInteractionTrigger(arg1) {
  return window['go']['main']['App']['DeleteInteractionTrigger'](arg1);
}

export function DeleteMCPAgent(arg1) {
  return window['go']['main']['App']['DeleteMCPAgent'](arg1);
}

export function DeleteMCPAgentFull(arg1) {
  return window['go']['main']['App']['DeleteMCPAgentFull'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function DeleteMessages(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessages'](arg1, arg2);
}

export function DeleteOAuthConnection(arg1) {
  return window['go']['main']['App']['DeleteOAuthConnection'](arg1);
}

export function DeleteVoiceProfile(arg1) {
  return window['go']['main']['App']['DeleteVoiceProfile'](arg1);
}

export function DisableVoiceHotkey() {
  return window['go']['main']['App']['DisableVoiceHotkey']();
}

export function DisconnectMCPAgent(arg1) {
  return window['go']['main']['App']['DisconnectMCPAgent'](arg1);
}

export function DisconnectOAuth(arg1) {
  return window['go']['main']['App']['DisconnectOAuth'](arg1);
}

export function EnableVoiceHotkey() {
  return window['go']['main']['App']['EnableVoiceHotkey']();
}

export function ExecuteTool(arg1) {
  return window['go']['main']['App']['ExecuteTool'](arg1);
}

export function ExportAgents(arg1, arg2) {
  return window['go']['main']['App']['ExportAgents'](arg1, arg2);
}

export function ExportConversations(arg1) {
  return window['go']['main']['App']['ExportConversations'](arg1);
}

export function ExportFAQs(arg1) {
  return window['go']['main']['App']['ExportFAQs'](arg1);
}

export function ExportInteractionProfiles(arg1) {
  return window['go']['main']['App']['ExportInteractionProfiles'](arg1);
}

export function ExportMemories(arg1) {
  return window['go']['main']['App']['ExportMemories'](arg1);
}

export function ExportVoiceProfiles(arg1) {
  return window['go']['main']['App']['ExportVoiceProfiles'](arg1);
}

export function ExtractTemplateVariables(arg1) {
  return window['go']['main']['App']['ExtractTemplateVariables'](arg1);
}

export function GenerateAllConversationEmbeddings() {
  return window['go']['main']['App']['GenerateAllConversationEmbeddings']();
}

export function GenerateAllFAQEmbeddings() {
  return window['go']['main']['App']['GenerateAllFAQEmbeddings']();
}

export function GenerateAllMemoryEmbeddings() {
  return window['go']['main']['App']['GenerateAllMemoryEmbeddings']();
}

export function GenerateConversationEmbedding(arg1) {
  return window['go']['main']['App']['GenerateConversationEmbedding'](arg1);
}

export function GenerateFAQEmbedding(arg1) {
  return window['go']['main']['App']['GenerateFAQEmbedding'](arg1);
}

export function GenerateImageDescription(arg1, arg2) {
  return window['go']['main']['App']['GenerateImageDescription'](arg1, arg2);
}

export function GenerateMemoryEmbedding(arg1) {
  return window['go']['main']['App']['GenerateMemoryEmbedding'](arg1);
}

export function GetActiveInteractionProfile() {
  return window['go']['main']['App']['GetActiveInteractionProfile']();
}

export function GetActiveOAuthConnectionForProvider(arg1) {
  return window['go']['main']['App']['GetActiveOAuthConnectionForProvider'](arg1);
}

export function GetActiveProfileHotkeys(arg1) {
  return window['go']['main']['App']['GetActiveProfileHotkeys'](arg1);
}

export function GetActiveTab() {
  return window['go']['main']['App']['GetActiveTab']();
}

export function GetAgentConfig(arg1) {
  return window['go']['main']['App']['GetAgentConfig'](arg1);
}

export function GetAgentConfigByID(arg1) {
  return window['go']['main']['App']['GetAgentConfigByID'](arg1);
}

export function GetAgentRegistry() {
  return window['go']['main']['App']['GetAgentRegistry']();
}

export function GetAllAgentConfigs() {
  return window['go']['main']['App']['GetAllAgentConfigs']();
}

export function GetAllFAQs() {
  return window['go']['main']['App']['GetAllFAQs']();
}

export function GetAllHTTPAgents() {
  return window['go']['main']['App']['GetAllHTTPAgents']();
}

export function GetAllHTTPAgentsFull() {
  return window['go']['main']['App']['GetAllHTTPAgentsFull']();
}

export function GetAllMCPAgents() {
  return window['go']['main']['App']['GetAllMCPAgents']();
}

export function GetAllMCPAgentsFull() {
  return window['go']['main']['App']['GetAllMCPAgentsFull']();
}

export function GetAllMemories() {
  return window['go']['main']['App']['GetAllMemories']();
}

export function GetAllModelCapabilities() {
  return window['go']['main']['App']['GetAllModelCapabilities']();
}

export function GetAllOAuthConnections() {
  return window['go']['main']['App']['GetAllOAuthConnections']();
}

export function GetAllTabs() {
  return window['go']['main']['App']['GetAllTabs']();
}

export function GetAllTokenStats() {
  return window['go']['main']['App']['GetAllTokenStats']();
}

export function GetAllVoiceProfiles() {
  return window['go']['main']['App']['GetAllVoiceProfiles']();
}

export function GetChatProfile(arg1) {
  return window['go']['main']['App']['GetChatProfile'](arg1);
}

export function GetChatProfiles() {
  return window['go']['main']['App']['GetChatProfiles']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversationEmbeddingStatus() {
  return window['go']['main']['App']['GetConversationEmbeddingStatus']();
}

export function GetConversationInfo(arg1) {
  return window['go']['main']['App']['GetConversationInfo'](arg1);
}

export function GetConversationModel(arg1) {
  return window['go']['main']['App']['GetConversationModel'](arg1);
}

export function GetConversationPreferences(arg1) {
  return window['go']['main']['App']['GetConversationPreferences'](arg1);
}

export function GetConversationSummary(arg1) {
  return window['go']['main']['App']['GetConversationSummary'](arg1);
}

export function GetConversationTokenStats(arg1) {
  return window['go']['main']['App']['GetConversationTokenStats'](arg1);
}

export function GetConversationWithThreads(arg1) {
  return window['go']['main']['App']['GetConversationWithThreads'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetCoreMemories() {
  return window['go']['main']['App']['GetCoreMemories']();
}

export function GetCurrentConversationID() {
  return window['go']['main']['App']['GetCurrentConversationID']();
}

export function GetCurrentTabID() {
  return window['go']['main']['App']['GetCurrentTabID']();
}

export function GetDefaultChatProfile() {
  return window['go']['main']['App']['GetDefaultChatProfile']();
}

export function GetDefaultInteractionProfile() {
  return window['go']['main']['App']['GetDefaultInteractionProfile']();
}

export function GetDefaultVoiceProfile() {
  return window['go']['main']['App']['GetDefaultVoiceProfile']();
}

export function GetEffectiveChatProfile(arg1) {
  return window['go']['main']['App']['GetEffectiveChatProfile'](arg1);
}

export function GetEffectiveModel(arg1) {
  return window['go']['main']['App']['GetEffectiveModel'](arg1);
}

export function GetEffectiveVoiceProfile(arg1) {
  return window['go']['main']['App']['GetEffectiveVoiceProfile'](arg1);
}

export function GetFAQ(arg1) {
  return window['go']['main']['App']['GetFAQ'](arg1);
}

export function GetFAQEmbeddingStatus() {
  return window['go']['main']['App']['GetFAQEmbeddingStatus']();
}

export function GetFileAgentAuthorizedPaths() {
  return window['go']['main']['App']['GetFileAgentAuthorizedPaths']();
}

export function GetFileAgentProtectedPaths() {
  return window['go']['main']['App']['GetFileAgentProtectedPaths']();
}

export function GetGlobalHotkeys() {
  return window['go']['main']['App']['GetGlobalHotkeys']();
}

export function GetHTTPAgent(arg1) {
  return window['go']['main']['App']['GetHTTPAgent'](arg1);
}

export function GetHTTPAgentByConfigID(arg1) {
  return window['go']['main']['App']['GetHTTPAgentByConfigID'](arg1);
}

export function GetHTTPAgentFull(arg1) {
  return window['go']['main']['App']['GetHTTPAgentFull'](arg1);
}

export function GetHTTPEndpoint(arg1) {
  return window['go']['main']['App']['GetHTTPEndpoint'](arg1);
}

export function GetHTTPEndpointsByAgentID(arg1) {
  return window['go']['main']['App']['GetHTTPEndpointsByAgentID'](arg1);
}

export function GetImageModel() {
  return window['go']['main']['App']['GetImageModel']();
}

export function GetInteractionProfile(arg1) {
  return window['go']['main']['App']['GetInteractionProfile'](arg1);
}

export function GetInteractionProfiles() {
  return window['go']['main']['App']['GetInteractionProfiles']();
}

export function GetInteractionTrigger(arg1) {
  return window['go']['main']['App']['GetInteractionTrigger'](arg1);
}

export function GetMCPAgent(arg1) {
  return window['go']['main']['App']['GetMCPAgent'](arg1);
}

export function GetMCPAgentByConfigID(arg1) {
  return window['go']['main']['App']['GetMCPAgentByConfigID'](arg1);
}

export function GetMCPAgentStatus(arg1) {
  return window['go']['main']['App']['GetMCPAgentStatus'](arg1);
}

export function GetMCPPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMCPPrompt'](arg1, arg2, arg3);
}

export function GetMCPPrompts(arg1) {
  return window['go']['main']['App']['GetMCPPrompts'](arg1);
}

export function GetMCPResourceTemplates(arg1) {
  return window['go']['main']['App']['GetMCPResourceTemplates'](arg1);
}

export function GetMCPResources(arg1) {
  return window['go']['main']['App']['GetMCPResources'](arg1);
}

export function GetMemoriesByCategory(arg1) {
  return window['go']['main']['App']['GetMemoriesByCategory'](arg1);
}

export function GetMemoriesWithoutEmbedding() {
  return window['go']['main']['App']['GetMemoriesWithoutEmbedding']();
}

export function GetMemoryEmbeddingStatus() {
  return window['go']['main']['App']['GetMemoryEmbeddingStatus']();
}

export function GetMessageChildren(arg1) {
  return window['go']['main']['App']['GetMessageChildren'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetModelCapability(arg1) {
  return window['go']['main']['App']['GetModelCapability'](arg1);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetOAuthAccessToken(arg1) {
  return window['go']['main']['App']['GetOAuthAccessToken'](arg1);
}

export function GetOAuthAccessTokenForProvider(arg1) {
  return window['go']['main']['App']['GetOAuthAccessTokenForProvider'](arg1);
}

export function GetOAuthConnection(arg1) {
  return window['go']['main']['App']['GetOAuthConnection'](arg1);
}

export function GetOAuthConnectionByProvider(arg1) {
  return window['go']['main']['App']['GetOAuthConnectionByProvider'](arg1);
}

export function GetOAuthConnections() {
  return window['go']['main']['App']['GetOAuthConnections']();
}

export function GetOAuthProviders() {
  return window['go']['main']['App']['GetOAuthProviders']();
}

export function GetOpenAITTSVoices() {
  return window['go']['main']['App']['GetOpenAITTSVoices']();
}

export function GetOrCreateModelCapability(arg1) {
  return window['go']['main']['App']['GetOrCreateModelCapability'](arg1);
}

export function GetRegisteredAgents() {
  return window['go']['main']['App']['GetRegisteredAgents']();
}

export function GetSAPI5Voices() {
  return window['go']['main']['App']['GetSAPI5Voices']();
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function GetToolsForAPI() {
  return window['go']['main']['App']['GetToolsForAPI']();
}

export function GetTriggersByProfile(arg1) {
  return window['go']['main']['App']['GetTriggersByProfile'](arg1);
}

export function GetVisionCapableModels() {
  return window['go']['main']['App']['GetVisionCapableModels']();
}

export function GetVoiceProfile(arg1) {
  return window['go']['main']['App']['GetVoiceProfile'](arg1);
}

export function GetVoiceProfileByName(arg1) {
  return window['go']['main']['App']['GetVoiceProfileByName'](arg1);
}

export function HardDeleteOAuthConnection(arg1) {
  return window['go']['main']['App']['HardDeleteOAuthConnection'](arg1);
}

export function HasImages(arg1) {
  return window['go']['main']['App']['HasImages'](arg1);
}

export function ImportAgents(arg1) {
  return window['go']['main']['App']['ImportAgents'](arg1);
}

export function ImportConversations(arg1) {
  return window['go']['main']['App']['ImportConversations'](arg1);
}

export function ImportFAQs(arg1) {
  return window['go']['main']['App']['ImportFAQs'](arg1);
}

export function ImportInteractionProfiles(arg1) {
  return window['go']['main']['App']['ImportInteractionProfiles'](arg1);
}

export function ImportMemories(arg1) {
  return window['go']['main']['App']['ImportMemories'](arg1);
}

export function ImportOpenAPIToHTTPAgent(arg1, arg2) {
  return window['go']['main']['App']['ImportOpenAPIToHTTPAgent'](arg1, arg2);
}

export function ImportPostmanToHTTPAgent(arg1, arg2) {
  return window['go']['main']['App']['ImportPostmanToHTTPAgent'](arg1, arg2);
}

export function ImportVoiceProfiles(arg1) {
  return window['go']['main']['App']['ImportVoiceProfiles'](arg1);
}

export function IncrementModelUsage(arg1) {
  return window['go']['main']['App']['IncrementModelUsage'](arg1);
}

export function InitSpeechManager(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InitSpeechManager'](arg1, arg2, arg3, arg4, arg5);
}

export function IsGlobalHotkeySupported() {
  return window['go']['main']['App']['IsGlobalHotkeySupported']();
}

export function IsSAPI5Speaking() {
  return window['go']['main']['App']['IsSAPI5Speaking']();
}

export function LoadConversationInTab(arg1, arg2) {
  return window['go']['main']['App']['LoadConversationInTab'](arg1, arg2);
}

export function ModelSupportsVision(arg1) {
  return window['go']['main']['App']['ModelSupportsVision'](arg1);
}

export function OnTabClosed(arg1) {
  return window['go']['main']['App']['OnTabClosed'](arg1);
}

export function OnTabInactive(arg1) {
  return window['go']['main']['App']['OnTabInactive'](arg1);
}

export function OpenConversationInCurrentTab(arg1) {
  return window['go']['main']['App']['OpenConversationInCurrentTab'](arg1);
}

export function OpenConversationInNewTab(arg1) {
  return window['go']['main']['App']['OpenConversationInNewTab'](arg1);
}

export function ParseOpenAPISpec(arg1) {
  return window['go']['main']['App']['ParseOpenAPISpec'](arg1);
}

export function ParsePostmanCollection(arg1) {
  return window['go']['main']['App']['ParsePostmanCollection'](arg1);
}

export function PreviewVoiceProfile(arg1, arg2) {
  return window['go']['main']['App']['PreviewVoiceProfile'](arg1, arg2);
}

export function PreviewVoiceSettings(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PreviewVoiceSettings'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ReadMCPResource(arg1, arg2) {
  return window['go']['main']['App']['ReadMCPResource'](arg1, arg2);
}

export function RefreshOAuthConnection(arg1) {
  return window['go']['main']['App']['RefreshOAuthConnection'](arg1);
}

export function RegenerateFAQEmbeddings() {
  return window['go']['main']['App']['RegenerateFAQEmbeddings']();
}

export function RegenerateMemoryEmbeddings() {
  return window['go']['main']['App']['RegenerateMemoryEmbeddings']();
}

export function RegenerateSingleFAQEmbedding(arg1) {
  return window['go']['main']['App']['RegenerateSingleFAQEmbedding'](arg1);
}

export function RegenerateSingleMemoryEmbedding(arg1) {
  return window['go']['main']['App']['RegenerateSingleMemoryEmbedding'](arg1);
}

export function RegisterInteractionProfileHotkeys(arg1) {
  return window['go']['main']['App']['RegisterInteractionProfileHotkeys'](arg1);
}

export function ReloadHTTPAgent(arg1) {
  return window['go']['main']['App']['ReloadHTTPAgent'](arg1);
}

export function ReloadLLMClient() {
  return window['go']['main']['App']['ReloadLLMClient']();
}

export function ReloadMCPAgent(arg1) {
  return window['go']['main']['App']['ReloadMCPAgent'](arg1);
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function RenameTab(arg1, arg2) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2);
}

export function ReorderTabs(arg1) {
  return window['go']['main']['App']['ReorderTabs'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function SaveOrUpdateAgentConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveOrUpdateAgentConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchConversationHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchConversationHistory'](arg1, arg2, arg3);
}

export function SearchConversationsSemantic(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchConversationsSemantic'](arg1, arg2, arg3);
}

export function SearchFAQ(arg1) {
  return window['go']['main']['App']['SearchFAQ'](arg1);
}

export function SearchFAQSemantic(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFAQSemantic'](arg1, arg2, arg3);
}

export function SearchInteractionProfiles(arg1) {
  return window['go']['main']['App']['SearchInteractionProfiles'](arg1);
}

export function SearchMemories(arg1) {
  return window['go']['main']['App']['SearchMemories'](arg1);
}

export function SearchOpenTabs(arg1, arg2) {
  return window['go']['main']['App']['SearchOpenTabs'](arg1, arg2);
}

export function SearchVoiceProfiles(arg1) {
  return window['go']['main']['App']['SearchVoiceProfiles'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendMessageSync(arg1, arg2) {
  return window['go']['main']['App']['SendMessageSync'](arg1, arg2);
}

export function SetActiveInteractionProfile(arg1) {
  return window['go']['main']['App']['SetActiveInteractionProfile'](arg1);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function SetChatModel(arg1) {
  return window['go']['main']['App']['SetChatModel'](arg1);
}

export function SetConversationChatProfile(arg1, arg2) {
  return window['go']['main']['App']['SetConversationChatProfile'](arg1, arg2);
}

export function SetConversationModel(arg1, arg2) {
  return window['go']['main']['App']['SetConversationModel'](arg1, arg2);
}

export function SetConversationVoiceProfile(arg1, arg2) {
  return window['go']['main']['App']['SetConversationVoiceProfile'](arg1, arg2);
}

export function SetDefaultChatProfile(arg1) {
  return window['go']['main']['App']['SetDefaultChatProfile'](arg1);
}

export function SetDefaultInteractionProfile(arg1) {
  return window['go']['main']['App']['SetDefaultInteractionProfile'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetDefaultVoiceProfile(arg1) {
  return window['go']['main']['App']['SetDefaultVoiceProfile'](arg1);
}

export function SetImageModel(arg1) {
  return window['go']['main']['App']['SetImageModel'](arg1);
}

export function SetModelError(arg1, arg2) {
  return window['go']['main']['App']['SetModelError'](arg1, arg2);
}

export function SetModelToolsSupport(arg1, arg2) {
  return window['go']['main']['App']['SetModelToolsSupport'](arg1, arg2);
}

export function SetModelVisionSupport(arg1, arg2) {
  return window['go']['main']['App']['SetModelVisionSupport'](arg1, arg2);
}

export function SetOpenAITTSSpeed(arg1) {
  return window['go']['main']['App']['SetOpenAITTSSpeed'](arg1);
}

export function SetOpenAITTSVoice(arg1) {
  return window['go']['main']['App']['SetOpenAITTSVoice'](arg1);
}

export function SetSAPI5Rate(arg1) {
  return window['go']['main']['App']['SetSAPI5Rate'](arg1);
}

export function SetSAPI5Volume(arg1) {
  return window['go']['main']['App']['SetSAPI5Volume'](arg1);
}

export function SetVoiceHotkey(arg1, arg2) {
  return window['go']['main']['App']['SetVoiceHotkey'](arg1, arg2);
}

export function SpeakSAPI5(arg1, arg2) {
  return window['go']['main']['App']['SpeakSAPI5'](arg1, arg2);
}

export function StartOAuthFlow(arg1, arg2) {
  return window['go']['main']['App']['StartOAuthFlow'](arg1, arg2);
}

export function StopSAPI5() {
  return window['go']['main']['App']['StopSAPI5']();
}

export function SwitchToTab(arg1) {
  return window['go']['main']['App']['SwitchToTab'](arg1);
}

export function SynthesizeOpenAI(arg1) {
  return window['go']['main']['App']['SynthesizeOpenAI'](arg1);
}

export function SynthesizeOpenAIStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['SynthesizeOpenAIStream'](arg1, arg2, arg3);
}

export function SynthesizeOpenAIWithVoice(arg1, arg2) {
  return window['go']['main']['App']['SynthesizeOpenAIWithVoice'](arg1, arg2);
}

export function TestAgent(arg1, arg2) {
  return window['go']['main']['App']['TestAgent'](arg1, arg2);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function TestConnectionWithModels() {
  return window['go']['main']['App']['TestConnectionWithModels']();
}

export function TestEmbeddings() {
  return window['go']['main']['App']['TestEmbeddings']();
}

export function TestFileAgent(arg1) {
  return window['go']['main']['App']['TestFileAgent'](arg1);
}

export function TestHTTPEndpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestHTTPEndpoint'](arg1, arg2, arg3);
}

export function TestHotReload() {
  return window['go']['main']['App']['TestHotReload']();
}

export function TestMCPAgent(arg1, arg2) {
  return window['go']['main']['App']['TestMCPAgent'](arg1, arg2);
}

export function TranscribeWhisper(arg1, arg2) {
  return window['go']['main']['App']['TranscribeWhisper'](arg1, arg2);
}

export function UnregisterInteractionProfileHotkeys(arg1) {
  return window['go']['main']['App']['UnregisterInteractionProfileHotkeys'](arg1);
}

export function UpdateAgentConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateAgentConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateChatProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatProfile'](arg1, arg2);
}

export function UpdateConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConversation'](arg1, arg2, arg3);
}

export function UpdateConversationModel(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationModel'](arg1, arg2);
}

export function UpdateConversationPreferences(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationPreferences'](arg1, arg2);
}

export function UpdateConversationSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationSettings'](arg1, arg2);
}

export function UpdateFAQ(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateFAQ'](arg1, arg2, arg3, arg4);
}

export function UpdateFileAgentAuthorizedPath(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateFileAgentAuthorizedPath'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateHTTPAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateHTTPAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateHTTPAgentFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['UpdateHTTPAgentFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function UpdateHTTPEndpoint(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['UpdateHTTPEndpoint'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function UpdateInteractionProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateInteractionProfile'](arg1, arg2);
}

export function UpdateInteractionTrigger(arg1, arg2) {
  return window['go']['main']['App']['UpdateInteractionTrigger'](arg1, arg2);
}

export function UpdateMCPAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['UpdateMCPAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function UpdateMCPAgentFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17) {
  return window['go']['main']['App']['UpdateMCPAgentFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
}

export function UpdateMemory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMemory'](arg1, arg2, arg3, arg4);
}

export function UpdateMessage(arg1, arg2) {
  return window['go']['main']['App']['UpdateMessage'](arg1, arg2);
}

export function UpdateModelCapability(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateModelCapability'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateOAuthConnectionLastUsed(arg1) {
  return window['go']['main']['App']['UpdateOAuthConnectionLastUsed'](arg1);
}

export function UpdateOAuthTokens(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateOAuthTokens'](arg1, arg2, arg3, arg4);
}

export function UpdateTabTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTabTitle'](arg1, arg2);
}

export function UpdateVoiceProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateVoiceProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateVoiceProfileFull(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['UpdateVoiceProfileFull'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function ValidateTemplate(arg1) {
  return window['go']['main']['App']['ValidateTemplate'](arg1);
}

// Skills bindings
export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSkillContent(arg1) {
  return window['go']['main']['App']['GetSkillContent'](arg1);
}

export function ReloadSkills() {
  return window['go']['main']['App']['ReloadSkills']();
}

// Profile bindings (unified)
export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetActiveProfileName() {
  return window['go']['main']['App']['GetActiveProfileName']();
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ReloadProfiles() {
  return window['go']['main']['App']['ReloadProfiles']();
}
