// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {allowlist} from '../models';
import {profiles} from '../models';
import {terminal} from '../models';
import {main} from '../models';
import {config} from '../models';
import {mcp} from '../models';
import {llm} from '../models';

export function AddChildMessage(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<database.ChatMessage>;

export function AddMessage(arg1:number,arg2:string,arg3:string):Promise<database.ChatMessage>;

export function AddMessageWithMedia(arg1:number,arg2:string,arg3:string,arg4:string):Promise<database.ChatMessage>;

export function AddMessageWithTokens(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:string):Promise<database.ChatMessage>;

export function AddMessageWithTokensAndMedia(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:string):Promise<database.ChatMessage>;

export function ClearConversation(arg1:number):Promise<void>;

export function ClearTab(arg1:number):Promise<void>;

export function CloseTab(arg1:number):Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function ConnectMCPServer(arg1:string):Promise<void>;

export function CreateAllowlist(arg1:allowlist.Allowlist):Promise<string>;

export function CreateConversation(arg1:string,arg2:string):Promise<database.Conversation>;

export function CreateMessage(arg1:number,arg2:string,arg3:string):Promise<database.ChatMessage>;

export function CreateNewConversation(arg1:string):Promise<number>;

export function CreateProfile(arg1:profiles.Profile):Promise<string>;

export function CreateTab(arg1:string,arg2:string,arg3:boolean):Promise<database.ChatTab>;

export function CreateTerminalSession(arg1:string):Promise<terminal.SessionInfo>;

export function DeleteAllowlist(arg1:string):Promise<void>;

export function DeleteConversation(arg1:number):Promise<void>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function DeleteMessage(arg1:number):Promise<void>;

export function DeleteMessages(arg1:number,arg2:Array<number>):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DisconnectMCPServer(arg1:string):Promise<void>;

export function ExportConversations(arg1:Array<number>):Promise<string>;

export function GetActiveProfile():Promise<profiles.Profile>;

export function GetActiveProfileSlug():Promise<string>;

export function GetActiveTab():Promise<database.ChatTab>;

export function GetAllTabs():Promise<Array<database.ChatTab>>;

export function GetAllTokenStats():Promise<Record<string, number>>;

export function GetAllowlist(arg1:string):Promise<allowlist.Allowlist>;

export function GetAllowlistSearchPaths():Promise<Array<string>>;

export function GetAllowlists():Promise<Array<allowlist.AllowlistInfo>>;

export function GetAvailableTools():Promise<Array<main.ToolInfo>>;

export function GetConfig():Promise<config.Config>;

export function GetConversation(arg1:number):Promise<database.Conversation>;

export function GetConversationInfo(arg1:number):Promise<database.Conversation>;

export function GetConversationTokenStats(arg1:number):Promise<Record<string, number>>;

export function GetConversationWithThreads(arg1:number):Promise<main.ConversationWithThreads>;

export function GetConversations():Promise<Array<database.Conversation>>;

export function GetCurrentConversationID():Promise<number>;

export function GetCurrentTabID():Promise<number>;

export function GetEffectiveModel():Promise<string>;

export function GetMCPServerConfig(arg1:string):Promise<mcp.ServerConfig>;

export function GetMCPServerTools(arg1:string):Promise<Array<mcp.MCPToolInfo>>;

export function GetMessageChildren(arg1:number):Promise<Array<main.MessageNode>>;

export function GetMessages(arg1:number,arg2:any):Promise<Array<main.MessageNode>>;

export function GetModels():Promise<Array<string>>;

export function GetOpenAITTSVoices():Promise<Array<main.OpenAITTSVoiceInfo>>;

export function GetProfile(arg1:string):Promise<profiles.Profile>;

export function GetProfileSearchPaths():Promise<Array<string>>;

export function GetProfiles():Promise<Array<profiles.ProfileInfo>>;

export function GetSAPI5Voices():Promise<Array<main.SAPI5VoiceInfo>>;

export function GetTabs():Promise<main.TabsResponse>;

export function GetTerminalHistory(arg1:string):Promise<Array<terminal.HistoryEntry>>;

export function GetTerminalStats():Promise<terminal.ManagerStats>;

export function ImportConversations(arg1:string):Promise<main.ImportResult>;

export function InitSpeechManager(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function InterruptTerminalCommand(arg1:string):Promise<void>;

export function IsGlobalHotkeySupported():Promise<boolean>;

export function IsSAPI5Speaking():Promise<boolean>;

export function ListMCPServers():Promise<Array<mcp.ServerInfo>>;

export function ListTerminalSessions():Promise<Array<terminal.SessionInfo>>;

export function LoadConversationInTab(arg1:number,arg2:number):Promise<void>;

export function OpenConversationInCurrentTab(arg1:number):Promise<void>;

export function OpenConversationInNewTab(arg1:number):Promise<number>;

export function PreviewVoiceSettings(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:string):Promise<void>;

export function ReconnectMCPServer(arg1:string):Promise<void>;

export function ReloadLLMClient():Promise<void>;

export function RenameConversation(arg1:number,arg2:string):Promise<void>;

export function RenameTab(arg1:number,arg2:string):Promise<void>;

export function ReorderTabs(arg1:Array<number>):Promise<void>;

export function ResetConfig():Promise<void>;

export function ResetDatabase():Promise<void>;

export function RespondCommandConfirmation(arg1:string,arg2:boolean):Promise<void>;

export function RunTerminalCommand(arg1:string,arg2:string):Promise<void>;

export function SaveMCPServer(arg1:string,arg2:mcp.ServerConfig):Promise<void>;

export function SaveSettings(arg1:llm.SettingsInput):Promise<void>;

export function SendMessage(arg1:number,arg2:string,arg3:string,arg4:llm.ChatParams):Promise<number>;

export function SendMessageSync(arg1:Array<llm.Message>,arg2:llm.ChatParams):Promise<string>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetActiveTab(arg1:number):Promise<void>;

export function SetChatModel(arg1:string):Promise<void>;

export function SetConversationModel(arg1:number,arg2:string):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetOpenAITTSSpeed(arg1:number):Promise<void>;

export function SetOpenAITTSVoice(arg1:string):Promise<void>;

export function SetSAPI5Rate(arg1:number):Promise<void>;

export function SetSAPI5Volume(arg1:number):Promise<void>;

export function SpeakSAPI5(arg1:string,arg2:string):Promise<void>;

export function StopSAPI5():Promise<void>;

export function SwitchToTab(arg1:number):Promise<void>;

export function SynthesizeOpenAI(arg1:string):Promise<main.SynthesisResultInfo>;

export function SynthesizeOpenAIStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SynthesizeOpenAIWithVoice(arg1:string,arg2:string):Promise<main.SynthesisResultInfo>;

export function TestConnection():Promise<boolean>;

export function TestConnectionWithModels():Promise<Array<string>>;

export function TranscribeWhisper(arg1:string,arg2:string):Promise<main.TranscriptionResultInfo>;

export function UpdateAllowlist(arg1:string,arg2:allowlist.Allowlist):Promise<void>;

export function UpdateConversation(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateConversationModel(arg1:number,arg2:string):Promise<void>;

export function UpdateMessage(arg1:number,arg2:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:profiles.Profile):Promise<void>;

export function UpdateTabTitle(arg1:number,arg2:string):Promise<void>;
