// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChildMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddChildMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function AddMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMessage'](arg1, arg2, arg3);
}

export function AddMessageWithMedia(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddMessageWithMedia'](arg1, arg2, arg3, arg4);
}

export function AddMessageWithTokens(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddMessageWithTokens'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddMessageWithTokensAndMedia(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddMessageWithTokensAndMedia'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AssignConversationToChannel(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssignConversationToChannel'](arg1, arg2, arg3);
}

export function AuthorizeMessagingContact(arg1, arg2) {
  return window['go']['main']['App']['AuthorizeMessagingContact'](arg1, arg2);
}

export function ClearConversation(arg1) {
  return window['go']['main']['App']['ClearConversation'](arg1);
}

export function ClearTab(arg1) {
  return window['go']['main']['App']['ClearTab'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function ConnectMCPServer(arg1) {
  return window['go']['main']['App']['ConnectMCPServer'](arg1);
}

export function CreateAllowlist(arg1) {
  return window['go']['main']['App']['CreateAllowlist'](arg1);
}

export function CreateConversation(arg1, arg2) {
  return window['go']['main']['App']['CreateConversation'](arg1, arg2);
}

export function CreateMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMessage'](arg1, arg2, arg3);
}

export function CreateNewConversation(arg1) {
  return window['go']['main']['App']['CreateNewConversation'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['main']['App']['CreateSkill'](arg1);
}

export function CreateTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTab'](arg1, arg2, arg3);
}

export function CreateTerminalSession(arg1) {
  return window['go']['main']['App']['CreateTerminalSession'](arg1);
}

export function DeleteAllowlist(arg1) {
  return window['go']['main']['App']['DeleteAllowlist'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function DeleteMessages(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessages'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['main']['App']['DisconnectMCPServer'](arg1);
}

export function ExportConversations(arg1) {
  return window['go']['main']['App']['ExportConversations'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetActiveProfileSlug() {
  return window['go']['main']['App']['GetActiveProfileSlug']();
}

export function GetActiveTab() {
  return window['go']['main']['App']['GetActiveTab']();
}

export function GetAllTabs() {
  return window['go']['main']['App']['GetAllTabs']();
}

export function GetAllTokenStats() {
  return window['go']['main']['App']['GetAllTokenStats']();
}

export function GetAllowlist(arg1) {
  return window['go']['main']['App']['GetAllowlist'](arg1);
}

export function GetAllowlistSearchPaths() {
  return window['go']['main']['App']['GetAllowlistSearchPaths']();
}

export function GetAllowlists() {
  return window['go']['main']['App']['GetAllowlists']();
}

export function GetAvailableChannels() {
  return window['go']['main']['App']['GetAvailableChannels']();
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversationChannel(arg1) {
  return window['go']['main']['App']['GetConversationChannel'](arg1);
}

export function GetConversationInfo(arg1) {
  return window['go']['main']['App']['GetConversationInfo'](arg1);
}

export function GetConversationTokenStats(arg1) {
  return window['go']['main']['App']['GetConversationTokenStats'](arg1);
}

export function GetConversationWithThreads(arg1) {
  return window['go']['main']['App']['GetConversationWithThreads'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetCurrentConversationID() {
  return window['go']['main']['App']['GetCurrentConversationID']();
}

export function GetCurrentTabID() {
  return window['go']['main']['App']['GetCurrentTabID']();
}

export function GetEffectiveModel() {
  return window['go']['main']['App']['GetEffectiveModel']();
}

export function GetMCPServerConfig(arg1) {
  return window['go']['main']['App']['GetMCPServerConfig'](arg1);
}

export function GetMCPServerTools(arg1) {
  return window['go']['main']['App']['GetMCPServerTools'](arg1);
}

export function GetMessageChildren(arg1) {
  return window['go']['main']['App']['GetMessageChildren'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetMessagingConfig() {
  return window['go']['main']['App']['GetMessagingConfig']();
}

export function GetMessagingStatus() {
  return window['go']['main']['App']['GetMessagingStatus']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetOpenAITTSVoices() {
  return window['go']['main']['App']['GetOpenAITTSVoices']();
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfileSearchPaths() {
  return window['go']['main']['App']['GetProfileSearchPaths']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSAPI5Voices() {
  return window['go']['main']['App']['GetSAPI5Voices']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetSkillSearchPaths() {
  return window['go']['main']['App']['GetSkillSearchPaths']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function GetTerminalHistory(arg1) {
  return window['go']['main']['App']['GetTerminalHistory'](arg1);
}

export function GetTerminalStats() {
  return window['go']['main']['App']['GetTerminalStats']();
}

export function GetUserInvocableSkills() {
  return window['go']['main']['App']['GetUserInvocableSkills']();
}

export function ImportConversations(arg1) {
  return window['go']['main']['App']['ImportConversations'](arg1);
}

export function InitSpeechManager(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InitSpeechManager'](arg1, arg2, arg3, arg4, arg5);
}

export function InterruptTerminalCommand(arg1) {
  return window['go']['main']['App']['InterruptTerminalCommand'](arg1);
}

export function IsGlobalHotkeySupported() {
  return window['go']['main']['App']['IsGlobalHotkeySupported']();
}

export function IsSAPI5Speaking() {
  return window['go']['main']['App']['IsSAPI5Speaking']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListTerminalSessions() {
  return window['go']['main']['App']['ListTerminalSessions']();
}

export function LoadConversationInTab(arg1, arg2) {
  return window['go']['main']['App']['LoadConversationInTab'](arg1, arg2);
}

export function OpenConversationInCurrentTab(arg1) {
  return window['go']['main']['App']['OpenConversationInCurrentTab'](arg1);
}

export function OpenConversationInNewTab(arg1) {
  return window['go']['main']['App']['OpenConversationInNewTab'](arg1);
}

export function PreviewVoiceSettings(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PreviewVoiceSettings'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ReconnectMCPServer(arg1) {
  return window['go']['main']['App']['ReconnectMCPServer'](arg1);
}

export function ReloadLLMClient() {
  return window['go']['main']['App']['ReloadLLMClient']();
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function RenameTab(arg1, arg2) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2);
}

export function ReorderTabs(arg1) {
  return window['go']['main']['App']['ReorderTabs'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function RespondCommandConfirmation(arg1, arg2) {
  return window['go']['main']['App']['RespondCommandConfirmation'](arg1, arg2);
}

export function RunTerminalCommand(arg1, arg2) {
  return window['go']['main']['App']['RunTerminalCommand'](arg1, arg2);
}

export function SaveMCPServer(arg1, arg2) {
  return window['go']['main']['App']['SaveMCPServer'](arg1, arg2);
}

export function SaveMessagingConfig(arg1) {
  return window['go']['main']['App']['SaveMessagingConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendMessageFromChannel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMessageFromChannel'](arg1, arg2, arg3, arg4, arg5);
}

export function SendMessageSync(arg1, arg2) {
  return window['go']['main']['App']['SendMessageSync'](arg1, arg2);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function SetChatModel(arg1) {
  return window['go']['main']['App']['SetChatModel'](arg1);
}

export function SetConversationModel(arg1, arg2) {
  return window['go']['main']['App']['SetConversationModel'](arg1, arg2);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetOpenAITTSSpeed(arg1) {
  return window['go']['main']['App']['SetOpenAITTSSpeed'](arg1);
}

export function SetOpenAITTSVoice(arg1) {
  return window['go']['main']['App']['SetOpenAITTSVoice'](arg1);
}

export function SetSAPI5Rate(arg1) {
  return window['go']['main']['App']['SetSAPI5Rate'](arg1);
}

export function SetSAPI5Volume(arg1) {
  return window['go']['main']['App']['SetSAPI5Volume'](arg1);
}

export function SignalCheckAPI(arg1) {
  return window['go']['main']['App']['SignalCheckAPI'](arg1);
}

export function SignalLink(arg1, arg2) {
  return window['go']['main']['App']['SignalLink'](arg1, arg2);
}

export function SignalLinkRaw(arg1, arg2) {
  return window['go']['main']['App']['SignalLinkRaw'](arg1, arg2);
}

export function SignalListAccounts(arg1) {
  return window['go']['main']['App']['SignalListAccounts'](arg1);
}

export function SignalRegister(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SignalRegister'](arg1, arg2, arg3, arg4);
}

export function SignalUnregister(arg1, arg2, arg3) {
  return window['go']['main']['App']['SignalUnregister'](arg1, arg2, arg3);
}

export function SignalVerify(arg1, arg2, arg3) {
  return window['go']['main']['App']['SignalVerify'](arg1, arg2, arg3);
}

export function SpeakSAPI5(arg1, arg2) {
  return window['go']['main']['App']['SpeakSAPI5'](arg1, arg2);
}

export function StopSAPI5() {
  return window['go']['main']['App']['StopSAPI5']();
}

export function SwitchToTab(arg1) {
  return window['go']['main']['App']['SwitchToTab'](arg1);
}

export function SynthesizeOpenAI(arg1) {
  return window['go']['main']['App']['SynthesizeOpenAI'](arg1);
}

export function SynthesizeOpenAIStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['SynthesizeOpenAIStream'](arg1, arg2, arg3);
}

export function SynthesizeOpenAIWithVoice(arg1, arg2) {
  return window['go']['main']['App']['SynthesizeOpenAIWithVoice'](arg1, arg2);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function TestConnectionWithModels() {
  return window['go']['main']['App']['TestConnectionWithModels']();
}

export function TranscribeWhisper(arg1, arg2) {
  return window['go']['main']['App']['TranscribeWhisper'](arg1, arg2);
}

export function UnassignConversationFromChannel(arg1) {
  return window['go']['main']['App']['UnassignConversationFromChannel'](arg1);
}

export function UpdateAllowlist(arg1, arg2) {
  return window['go']['main']['App']['UpdateAllowlist'](arg1, arg2);
}

export function UpdateConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConversation'](arg1, arg2, arg3);
}

export function UpdateConversationModel(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationModel'](arg1, arg2);
}

export function UpdateMessage(arg1, arg2) {
  return window['go']['main']['App']['UpdateMessage'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function UpdateProfileMediaSupport(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileMediaSupport'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2);
}

export function UpdateTabTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTabTitle'](arg1, arg2);
}
