// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';
import {time} from '../models';
import {llm} from '../models';
import {agents} from '../models';
import {config} from '../models';

export function AddMessage(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<database.ChatMessage>;

export function AddMessageWithMedia(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<database.ChatMessage>;

export function AddMessageWithTokens(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:string):Promise<database.ChatMessage>;

export function AddMessageWithTokensAndMedia(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number,arg9:number,arg10:string):Promise<database.ChatMessage>;

export function ClearTab(arg1:number):Promise<void>;

export function CloseTab(arg1:number):Promise<void>;

export function CompleteOAuthFlow(arg1:string,arg2:number):Promise<main.OAuthConnectionInfo>;

export function ConnectMCPAgent(arg1:number):Promise<void>;

export function CreateAgentConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<database.AgentConfig>;

export function CreateConversation(arg1:string,arg2:string):Promise<database.Conversation>;

export function CreateFAQ(arg1:string,arg2:string,arg3:string):Promise<database.FAQ>;

export function CreateFileAgentAuthorizedPath(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<main.FileAgentAuthorizedPathInfo>;

export function CreateHTTPAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<database.HTTPAgent>;

export function CreateHTTPAgentFull(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:string,arg8:string,arg9:string,arg10:string,arg11:number,arg12:number):Promise<main.HTTPAgentFullConfig>;

export function CreateHTTPEndpoint(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<database.HTTPEndpoint>;

export function CreateInteractionProfile(arg1:database.InteractionProfile):Promise<database.InteractionProfile>;

export function CreateInteractionTrigger(arg1:database.InteractionTrigger):Promise<database.InteractionTrigger>;

export function CreateMCPAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:boolean):Promise<database.MCPAgentDB>;

export function CreateMCPAgentFull(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string,arg15:string,arg16:boolean,arg17:boolean):Promise<Record<string, any>>;

export function CreateMCPMessage(arg1:number,arg2:main.MCPSamplingRequestInfo):Promise<main.MCPSamplingResultInfo>;

export function CreateMemory(arg1:string,arg2:string,arg3:string):Promise<database.Memory>;

export function CreateOAuthConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:time.Time):Promise<database.OAuthConnection>;

export function CreateTab(arg1:string,arg2:string,arg3:boolean):Promise<database.ChatTab>;

export function CreateVoiceProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:boolean):Promise<database.VoiceProfile>;

export function CreateVoiceProfileFull(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:boolean,arg9:boolean,arg10:boolean):Promise<database.VoiceProfile>;

export function DeleteAgentConfig(arg1:number):Promise<void>;

export function DeleteConversation(arg1:number):Promise<void>;

export function DeleteFAQ(arg1:number):Promise<void>;

export function DeleteFileAgentAuthorizedPath(arg1:number):Promise<void>;

export function DeleteHTTPAgent(arg1:number):Promise<void>;

export function DeleteHTTPAgentFull(arg1:number):Promise<void>;

export function DeleteHTTPEndpoint(arg1:number):Promise<void>;

export function DeleteInteractionProfile(arg1:number):Promise<void>;

export function DeleteInteractionTrigger(arg1:number):Promise<void>;

export function DeleteMCPAgent(arg1:number):Promise<void>;

export function DeleteMCPAgentFull(arg1:number):Promise<void>;

export function DeleteMemory(arg1:number):Promise<void>;

export function DeleteOAuthConnection(arg1:number):Promise<void>;

export function DeleteVoiceProfile(arg1:number):Promise<void>;

export function DisableVoiceHotkey():Promise<void>;

export function DisconnectMCPAgent(arg1:number):Promise<void>;

export function DisconnectOAuth(arg1:number):Promise<void>;

export function EnableVoiceHotkey():Promise<void>;

export function ExecuteTool(arg1:llm.ToolCall):Promise<string>;

export function ExportAgents(arg1:Array<number>,arg2:Array<number>):Promise<string>;

export function ExportConversations(arg1:Array<number>):Promise<string>;

export function ExportFAQs(arg1:Array<number>):Promise<string>;

export function ExportMemories(arg1:Array<number>):Promise<string>;

export function ExportVoiceProfiles(arg1:Array<number>):Promise<string>;

export function ExtractTemplateVariables(arg1:string):Promise<Array<string>>;

export function GenerateAllFAQEmbeddings():Promise<number>;

export function GenerateFAQEmbedding(arg1:number):Promise<void>;

export function GenerateImageDescription(arg1:string,arg2:string):Promise<string>;

export function GetActiveInteractionProfile():Promise<database.InteractionProfile>;

export function GetActiveOAuthConnectionForProvider(arg1:string):Promise<database.OAuthConnection>;

export function GetActiveProfileHotkeys(arg1:number):Promise<Array<Record<string, any>>>;

export function GetActiveTab():Promise<database.ChatTab>;

export function GetAgentConfig(arg1:string):Promise<database.AgentConfig>;

export function GetAgentConfigByID(arg1:number):Promise<database.AgentConfig>;

export function GetAgentRegistry():Promise<agents.Registry>;

export function GetAllAgentConfigs():Promise<Array<database.AgentConfig>>;

export function GetAllFAQs():Promise<Array<database.FAQ>>;

export function GetAllHTTPAgents():Promise<Array<database.HTTPAgent>>;

export function GetAllHTTPAgentsFull():Promise<Array<main.HTTPAgentFullConfig>>;

export function GetAllMCPAgents():Promise<Array<database.MCPAgentDB>>;

export function GetAllMCPAgentsFull():Promise<Array<Record<string, any>>>;

export function GetAllMemories():Promise<Array<database.Memory>>;

export function GetAllModelCapabilities():Promise<Array<database.ModelCapability>>;

export function GetAllOAuthConnections():Promise<Array<database.OAuthConnection>>;

export function GetAllTabs():Promise<Array<database.ChatTab>>;

export function GetAllTokenStats():Promise<Record<string, number>>;

export function GetAllVoiceProfiles():Promise<Array<database.VoiceProfile>>;

export function GetConfig():Promise<config.Config>;

export function GetConversation(arg1:number):Promise<database.Conversation>;

export function GetConversationInfo(arg1:number):Promise<database.Conversation>;

export function GetConversationPreferences(arg1:number):Promise<database.ChatPreferences>;

export function GetConversationTokenStats(arg1:number):Promise<Record<string, number>>;

export function GetConversationWithThreads(arg1:number):Promise<main.ConversationWithThreads>;

export function GetConversations():Promise<Array<database.Conversation>>;

export function GetCoreMemories():Promise<Array<database.Memory>>;

export function GetDefaultInteractionProfile():Promise<database.InteractionProfile>;

export function GetDefaultVoiceProfile():Promise<database.VoiceProfile>;

export function GetEffectiveVoiceProfile(arg1:number):Promise<database.VoiceProfile>;

export function GetFAQ(arg1:number):Promise<database.FAQ>;

export function GetFAQEmbeddingStatus():Promise<main.FAQEmbeddingStatus>;

export function GetFileAgentAuthorizedPaths():Promise<Array<main.FileAgentAuthorizedPathInfo>>;

export function GetFileAgentProtectedPaths():Promise<Record<string, any>>;

export function GetGlobalHotkeys():Promise<Array<main.HotkeyInfo>>;

export function GetHTTPAgent(arg1:number):Promise<database.HTTPAgent>;

export function GetHTTPAgentByConfigID(arg1:number):Promise<database.HTTPAgent>;

export function GetHTTPAgentFull(arg1:number):Promise<main.HTTPAgentFullConfig>;

export function GetHTTPEndpoint(arg1:number):Promise<database.HTTPEndpoint>;

export function GetHTTPEndpointsByAgentID(arg1:number):Promise<Array<database.HTTPEndpoint>>;

export function GetImageModel():Promise<string>;

export function GetInteractionProfile(arg1:number):Promise<database.InteractionProfile>;

export function GetInteractionProfiles():Promise<Array<database.InteractionProfile>>;

export function GetInteractionTrigger(arg1:number):Promise<database.InteractionTrigger>;

export function GetMCPAgent(arg1:number):Promise<database.MCPAgentDB>;

export function GetMCPAgentByConfigID(arg1:number):Promise<database.MCPAgentDB>;

export function GetMCPAgentStatus(arg1:number):Promise<Record<string, any>>;

export function GetMCPPrompt(arg1:number,arg2:string,arg3:Record<string, string>):Promise<main.MCPPromptResultInfo>;

export function GetMCPPrompts(arg1:number):Promise<Array<main.MCPPromptInfo>>;

export function GetMCPResourceTemplates(arg1:number):Promise<Array<main.MCPResourceTemplateInfo>>;

export function GetMCPResources(arg1:number):Promise<Array<main.MCPResourceInfo>>;

export function GetMemoriesByCategory(arg1:string):Promise<Array<database.Memory>>;

export function GetMessageChildren(arg1:number):Promise<Array<main.MessageNode>>;

export function GetMessages(arg1:number,arg2:any):Promise<Array<main.MessageNode>>;

export function GetModelCapability(arg1:string):Promise<database.ModelCapability>;

export function GetModels():Promise<Array<string>>;

export function GetOAuthAccessToken(arg1:number):Promise<string>;

export function GetOAuthAccessTokenForProvider(arg1:string):Promise<string>;

export function GetOAuthConnection(arg1:number):Promise<database.OAuthConnection>;

export function GetOAuthConnectionByProvider(arg1:string):Promise<Array<database.OAuthConnection>>;

export function GetOAuthConnections():Promise<Array<main.OAuthConnectionInfo>>;

export function GetOAuthProviders():Promise<Array<main.OAuthProviderInfo>>;

export function GetOpenAITTSVoices():Promise<Array<main.OpenAITTSVoiceInfo>>;

export function GetOrCreateModelCapability(arg1:string):Promise<database.ModelCapability>;

export function GetRegisteredAgents():Promise<Array<main.AgentInfo>>;

export function GetSAPI5Voices():Promise<Array<main.SAPI5VoiceInfo>>;

export function GetTabs():Promise<main.TabsResponse>;

export function GetToolsForAPI():Promise<Array<llm.Tool>>;

export function GetTriggersByProfile(arg1:number):Promise<Array<database.InteractionTrigger>>;

export function GetVisionCapableModels():Promise<Array<database.ModelCapability>>;

export function GetVoiceProfile(arg1:number):Promise<database.VoiceProfile>;

export function GetVoiceProfileByName(arg1:string):Promise<database.VoiceProfile>;

export function HardDeleteOAuthConnection(arg1:number):Promise<void>;

export function HasImages(arg1:Array<llm.Message>):Promise<boolean>;

export function ImportAgents(arg1:string):Promise<main.ImportResult>;

export function ImportConversations(arg1:string):Promise<main.ImportResult>;

export function ImportFAQs(arg1:string):Promise<main.ImportResult>;

export function ImportMemories(arg1:string):Promise<main.ImportResult>;

export function ImportOpenAPIToHTTPAgent(arg1:string,arg2:string):Promise<main.HTTPAgentFullConfig>;

export function ImportPostmanToHTTPAgent(arg1:string,arg2:string):Promise<main.HTTPAgentFullConfig>;

export function ImportVoiceProfiles(arg1:string):Promise<main.ImportResult>;

export function IncrementModelUsage(arg1:string):Promise<void>;

export function InitSpeechManager(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function IsGlobalHotkeySupported():Promise<boolean>;

export function IsSAPI5Speaking():Promise<boolean>;

export function LoadConversationInTab(arg1:number,arg2:number):Promise<void>;

export function ModelSupportsVision(arg1:string):Promise<boolean>;

export function ParseOpenAPISpec(arg1:string):Promise<main.OpenAPIImportResult>;

export function ParsePostmanCollection(arg1:string):Promise<main.OpenAPIImportResult>;

export function PreviewVoiceProfile(arg1:number,arg2:string):Promise<void>;

export function PreviewVoiceSettings(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:string):Promise<void>;

export function ReadMCPResource(arg1:number,arg2:string):Promise<main.MCPResourceContentInfo>;

export function RefreshOAuthConnection(arg1:number):Promise<void>;

export function RegenerateFAQEmbeddings():Promise<number>;

export function RegenerateSingleFAQEmbedding(arg1:number):Promise<void>;

export function RegisterInteractionProfileHotkeys(arg1:number):Promise<void>;

export function ReloadHTTPAgent(arg1:number):Promise<void>;

export function ReloadLLMClient():Promise<void>;

export function ReloadMCPAgent(arg1:number):Promise<void>;

export function ReorderTabs(arg1:Array<number>):Promise<void>;

export function ResetConfig():Promise<void>;

export function ResetDatabase():Promise<void>;

export function SaveOrUpdateAgentConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<database.AgentConfig>;

export function SaveSettings(arg1:llm.SettingsInput):Promise<void>;

export function SearchFAQ(arg1:string):Promise<Array<database.FAQ>>;

export function SearchFAQSemantic(arg1:string,arg2:number,arg3:number):Promise<Array<database.FAQ>>;

export function SearchInteractionProfiles(arg1:string):Promise<Array<database.InteractionProfile>>;

export function SearchMemories(arg1:string):Promise<Array<database.Memory>>;

export function SearchVoiceProfiles(arg1:string):Promise<Array<database.VoiceProfile>>;

export function SendMessage(arg1:number,arg2:string,arg3:string,arg4:llm.ChatParams):Promise<number>;

export function SendMessageSync(arg1:Array<llm.Message>,arg2:llm.ChatParams):Promise<string>;

export function SetActiveInteractionProfile(arg1:number):Promise<void>;

export function SetActiveTab(arg1:number):Promise<void>;

export function SetConversationVoiceProfile(arg1:number,arg2:number):Promise<void>;

export function SetDefaultInteractionProfile(arg1:number):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetDefaultVoiceProfile(arg1:number):Promise<void>;

export function SetImageModel(arg1:string):Promise<void>;

export function SetModelError(arg1:string,arg2:string):Promise<void>;

export function SetModelToolsSupport(arg1:string,arg2:boolean):Promise<void>;

export function SetModelVisionSupport(arg1:string,arg2:boolean):Promise<void>;

export function SetOpenAITTSSpeed(arg1:number):Promise<void>;

export function SetOpenAITTSVoice(arg1:string):Promise<void>;

export function SetSAPI5Rate(arg1:number):Promise<void>;

export function SetSAPI5Volume(arg1:number):Promise<void>;

export function SetVoiceHotkey(arg1:string,arg2:string):Promise<void>;

export function SpeakSAPI5(arg1:string,arg2:string):Promise<void>;

export function StartOAuthFlow(arg1:string,arg2:Array<string>):Promise<string>;

export function StopSAPI5():Promise<void>;

export function SynthesizeOpenAI(arg1:string):Promise<main.SynthesisResultInfo>;

export function SynthesizeOpenAIWithVoice(arg1:string,arg2:string):Promise<main.SynthesisResultInfo>;

export function TestAgent(arg1:string,arg2:string):Promise<string>;

export function TestConnection():Promise<boolean>;

export function TestConnectionWithModels():Promise<Array<string>>;

export function TestEmbeddings():Promise<string>;

export function TestFileAgent(arg1:string):Promise<string>;

export function TestHTTPEndpoint(arg1:number,arg2:string,arg3:string):Promise<string>;

export function TestHotReload():Promise<string>;

export function TestMCPAgent(arg1:number,arg2:string):Promise<string>;

export function TranscribeWhisper(arg1:string,arg2:string):Promise<main.TranscriptionResultInfo>;

export function UnregisterInteractionProfileHotkeys(arg1:number):Promise<void>;

export function UpdateAgentConfig(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<database.AgentConfig>;

export function UpdateConversation(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateConversationModel(arg1:number,arg2:string):Promise<void>;

export function UpdateConversationPreferences(arg1:number,arg2:database.ChatPreferences):Promise<void>;

export function UpdateConversationSettings(arg1:number,arg2:boolean):Promise<void>;

export function UpdateFAQ(arg1:number,arg2:string,arg3:string,arg4:string):Promise<database.FAQ>;

export function UpdateFileAgentAuthorizedPath(arg1:number,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<main.FileAgentAuthorizedPathInfo>;

export function UpdateHTTPAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<database.HTTPAgent>;

export function UpdateHTTPAgentFull(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:string,arg8:string,arg9:string,arg10:string,arg11:number,arg12:number):Promise<main.HTTPAgentFullConfig>;

export function UpdateHTTPEndpoint(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<database.HTTPEndpoint>;

export function UpdateInteractionProfile(arg1:number,arg2:database.InteractionProfile):Promise<database.InteractionProfile>;

export function UpdateInteractionTrigger(arg1:number,arg2:database.InteractionTrigger):Promise<database.InteractionTrigger>;

export function UpdateMCPAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:boolean):Promise<database.MCPAgentDB>;

export function UpdateMCPAgentFull(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string,arg15:string,arg16:boolean,arg17:boolean):Promise<Record<string, any>>;

export function UpdateMemory(arg1:number,arg2:string,arg3:string,arg4:string):Promise<database.Memory>;

export function UpdateModelCapability(arg1:string,arg2:any,arg3:any,arg4:any,arg5:any,arg6:any,arg7:any,arg8:any):Promise<database.ModelCapability>;

export function UpdateOAuthConnectionLastUsed(arg1:number):Promise<void>;

export function UpdateOAuthTokens(arg1:number,arg2:string,arg3:string,arg4:time.Time):Promise<void>;

export function UpdateTabTitle(arg1:number,arg2:string):Promise<void>;

export function UpdateVoiceProfile(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:boolean):Promise<database.VoiceProfile>;

export function UpdateVoiceProfileFull(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:boolean,arg10:boolean,arg11:boolean):Promise<database.VoiceProfile>;

export function ValidateTemplate(arg1:string):Promise<boolean|string>;
