// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {config} from '../models';
import {main} from '../models';
import {llm} from '../models';

export function AddChildMessage(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<database.ChatMessage>;

export function AddMessage(arg1:number,arg2:string,arg3:string):Promise<database.ChatMessage>;

export function AddMessageWithMedia(arg1:number,arg2:string,arg3:string,arg4:string):Promise<database.ChatMessage>;

export function AddMessageWithTokens(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:string):Promise<database.ChatMessage>;

export function AddMessageWithTokensAndMedia(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:string):Promise<database.ChatMessage>;

export function ClearConversation(arg1:number):Promise<void>;

export function ClearConversationChatProfile(arg1:number):Promise<void>;

export function ClearTab(arg1:number):Promise<void>;

export function CloseTab(arg1:number):Promise<void>;

export function CreateChatProfile(arg1:database.ChatProfile):Promise<database.ChatProfile>;

export function CreateConversation(arg1:string,arg2:string):Promise<database.Conversation>;

export function CreateInteractionProfile(arg1:database.InteractionProfile):Promise<database.InteractionProfile>;

export function CreateInteractionTrigger(arg1:database.InteractionTrigger):Promise<database.InteractionTrigger>;

export function CreateMessage(arg1:number,arg2:string,arg3:string):Promise<database.ChatMessage>;

export function CreateNewConversation(arg1:string):Promise<number>;

export function CreateTab(arg1:string,arg2:string,arg3:boolean):Promise<database.ChatTab>;

export function CreateVoiceProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:boolean):Promise<database.VoiceProfile>;

export function CreateVoiceProfileFull(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:boolean,arg9:boolean,arg10:boolean):Promise<database.VoiceProfile>;

export function DeleteChatProfile(arg1:number):Promise<void>;

export function DeleteConversation(arg1:number):Promise<void>;

export function DeleteInteractionProfile(arg1:number):Promise<void>;

export function DeleteInteractionTrigger(arg1:number):Promise<void>;

export function DeleteMessage(arg1:number):Promise<void>;

export function DeleteMessages(arg1:number,arg2:Array<number>):Promise<void>;

export function DeleteVoiceProfile(arg1:number):Promise<void>;

export function DisableVoiceHotkey():Promise<void>;

export function EnableVoiceHotkey():Promise<void>;

export function ExportConversations(arg1:Array<number>):Promise<string>;

export function ExportInteractionProfiles(arg1:Array<number>):Promise<string>;

export function ExportVoiceProfiles(arg1:Array<number>):Promise<string>;

export function GetActiveInteractionProfile():Promise<database.InteractionProfile>;

export function GetActiveProfileHotkeys(arg1:number):Promise<Array<Record<string, any>>>;

export function GetActiveTab():Promise<database.ChatTab>;

export function GetAllTabs():Promise<Array<database.ChatTab>>;

export function GetAllTokenStats():Promise<Record<string, number>>;

export function GetAllVoiceProfiles():Promise<Array<database.VoiceProfile>>;

export function GetChatProfile(arg1:number):Promise<database.ChatProfile>;

export function GetChatProfiles():Promise<Array<database.ChatProfile>>;

export function GetConfig():Promise<config.Config>;

export function GetConversation(arg1:number):Promise<database.Conversation>;

export function GetConversationInfo(arg1:number):Promise<database.Conversation>;

export function GetConversationModel(arg1:number):Promise<string>;

export function GetConversationPreferences(arg1:number):Promise<database.ChatPreferences>;

export function GetConversationTokenStats(arg1:number):Promise<Record<string, number>>;

export function GetConversationWithThreads(arg1:number):Promise<main.ConversationWithThreads>;

export function GetConversations():Promise<Array<database.Conversation>>;

export function GetCurrentConversationID():Promise<number>;

export function GetCurrentTabID():Promise<number>;

export function GetDefaultChatProfile():Promise<database.ChatProfile>;

export function GetDefaultInteractionProfile():Promise<database.InteractionProfile>;

export function GetDefaultVoiceProfile():Promise<database.VoiceProfile>;

export function GetEffectiveChatProfile(arg1:number):Promise<database.ChatProfile>;

export function GetEffectiveModel(arg1:number):Promise<string>;

export function GetEffectiveVoiceProfile(arg1:number):Promise<database.VoiceProfile>;

export function GetGlobalHotkeys():Promise<Array<main.HotkeyInfo>>;

export function GetInteractionProfile(arg1:number):Promise<database.InteractionProfile>;

export function GetInteractionProfiles():Promise<Array<database.InteractionProfile>>;

export function GetInteractionTrigger(arg1:number):Promise<database.InteractionTrigger>;

export function GetMessageChildren(arg1:number):Promise<Array<main.MessageNode>>;

export function GetMessages(arg1:number,arg2:any):Promise<Array<main.MessageNode>>;

export function GetModels():Promise<Array<string>>;

export function GetOpenAITTSVoices():Promise<Array<main.OpenAITTSVoiceInfo>>;

export function GetSAPI5Voices():Promise<Array<main.SAPI5VoiceInfo>>;

export function GetTabs():Promise<main.TabsResponse>;

export function GetTriggersByProfile(arg1:number):Promise<Array<database.InteractionTrigger>>;

export function GetVoiceProfile(arg1:number):Promise<database.VoiceProfile>;

export function GetVoiceProfileByName(arg1:string):Promise<database.VoiceProfile>;

export function ImportConversations(arg1:string):Promise<main.ImportResult>;

export function ImportInteractionProfiles(arg1:string):Promise<main.ImportResult>;

export function ImportVoiceProfiles(arg1:string):Promise<main.ImportResult>;

export function InitSpeechManager(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function IsGlobalHotkeySupported():Promise<boolean>;

export function IsSAPI5Speaking():Promise<boolean>;

export function LoadConversationInTab(arg1:number,arg2:number):Promise<void>;

export function OpenConversationInCurrentTab(arg1:number):Promise<void>;

export function OpenConversationInNewTab(arg1:number):Promise<number>;

export function PreviewVoiceProfile(arg1:number,arg2:string):Promise<void>;

export function PreviewVoiceSettings(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:string):Promise<void>;

export function RegisterInteractionProfileHotkeys(arg1:number):Promise<void>;

export function ReloadLLMClient():Promise<void>;

export function RenameConversation(arg1:number,arg2:string):Promise<void>;

export function RenameTab(arg1:number,arg2:string):Promise<void>;

export function ReorderTabs(arg1:Array<number>):Promise<void>;

export function ResetConfig():Promise<void>;

export function ResetDatabase():Promise<void>;

export function SaveSettings(arg1:llm.SettingsInput):Promise<void>;

export function SearchInteractionProfiles(arg1:string):Promise<Array<database.InteractionProfile>>;

export function SearchVoiceProfiles(arg1:string):Promise<Array<database.VoiceProfile>>;

export function SendMessage(arg1:number,arg2:string,arg3:string,arg4:llm.ChatParams):Promise<number>;

export function SendMessageSync(arg1:Array<llm.Message>,arg2:llm.ChatParams):Promise<string>;

export function SetActiveInteractionProfile(arg1:number):Promise<void>;

export function SetActiveTab(arg1:number):Promise<void>;

export function SetChatModel(arg1:string):Promise<void>;

export function SetConversationChatProfile(arg1:number,arg2:number):Promise<void>;

export function SetConversationModel(arg1:number,arg2:string):Promise<void>;

export function SetConversationVoiceProfile(arg1:number,arg2:number):Promise<void>;

export function SetDefaultChatProfile(arg1:number):Promise<void>;

export function SetDefaultInteractionProfile(arg1:number):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetDefaultVoiceProfile(arg1:number):Promise<void>;

export function SetOpenAITTSSpeed(arg1:number):Promise<void>;

export function SetOpenAITTSVoice(arg1:string):Promise<void>;

export function SetSAPI5Rate(arg1:number):Promise<void>;

export function SetSAPI5Volume(arg1:number):Promise<void>;

export function SetVoiceHotkey(arg1:string,arg2:string):Promise<void>;

export function SpeakSAPI5(arg1:string,arg2:string):Promise<void>;

export function StopSAPI5():Promise<void>;

export function SwitchToTab(arg1:number):Promise<void>;

export function SynthesizeOpenAI(arg1:string):Promise<main.SynthesisResultInfo>;

export function SynthesizeOpenAIStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SynthesizeOpenAIWithVoice(arg1:string,arg2:string):Promise<main.SynthesisResultInfo>;

export function TestConnection():Promise<boolean>;

export function TestConnectionWithModels():Promise<Array<string>>;

export function TranscribeWhisper(arg1:string,arg2:string):Promise<main.TranscriptionResultInfo>;

export function UnregisterInteractionProfileHotkeys(arg1:number):Promise<void>;

export function UpdateChatProfile(arg1:number,arg2:database.ChatProfile):Promise<database.ChatProfile>;

export function UpdateConversation(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateConversationModel(arg1:number,arg2:string):Promise<void>;

export function UpdateConversationPreferences(arg1:number,arg2:database.ChatPreferences):Promise<void>;

export function UpdateInteractionProfile(arg1:number,arg2:database.InteractionProfile):Promise<database.InteractionProfile>;

export function UpdateInteractionTrigger(arg1:number,arg2:database.InteractionTrigger):Promise<database.InteractionTrigger>;

export function UpdateMessage(arg1:number,arg2:string):Promise<void>;

export function UpdateTabTitle(arg1:number,arg2:string):Promise<void>;

export function UpdateVoiceProfile(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:boolean):Promise<database.VoiceProfile>;

export function UpdateVoiceProfileFull(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:boolean,arg10:boolean,arg11:boolean):Promise<database.VoiceProfile>;
